### PR TITLE
Coq upgrade

### PR DESCRIPTION
**Pull request by nieder**
This upgrades coq to the latest upstream (v8.19.1). The docs had to be merged back into the main package, unfortunately increasing the BDep load of the build, because I couldn't find a way to build the docs w/out the compiled bits that are present in a normal build tree using the new dune based build system.
I followed Debian's recipes and also created some new splitoffs to help with organization.

### CODE REVIEW

**Comment by cooljeanius** [comment]
I tried testing this PR, and it failed with the following message:
```
The package 'coq' will be built and installed.
Reading build dependency for coq-8.19.1-2...
WARNING: While resolving dependency "sphinxcontrib-bibtex-py310 >= 2.6.2" for package "coq-8.19.1-2", package "sphinxcontrib-bibtex-py310" was not found.
Can't resolve dependency "sphinxcontrib-bibtex-py310 (>= 2.6.2)" for package "coq-8.19.1-2" (no matching packages/versions found)
Exiting with failure.
```

**Comment by nieder** [comment]
Make sure you selfupdate. sphinxcontrib-bibtex in master was recently updated to have it available for this PR.

**Comment by cooljeanius** [comment]
it looks like that commit (738cc0bc38fe33c75bbf6c82f1003bfb2c971fe2) isn't in this branch yet...

**Review by cooljeanius — APPROVED** [review]
> it looks like that commit ([738cc0b](https://github.com/fink/fink-distributions/commit/738cc0bc38fe33c75bbf6c82f1003bfb2c971fe2)) isn't in this branch yet...

OK after cherry-picking that commit, I can confirm that coq built successfully for me

**Comment by nieder** [comment]
Great. Does it work correctly? I have no idea how to use it and unfortunately the tests don't work because they're missing some component that's not readily available when building a release.

**Comment by cooljeanius** [comment]
> Great. Does it work correctly? I have no idea how to use it and unfortunately the tests don't work because they're missing some component that's not readily available when building a release.

Well I just tested the `--help` flag for each of its executables, and ran into this from its executables ending in `.byte` (`coqc.byte` and `coqtop.byte`):
```
$ coqc.byte --help
Fatal error: cannot load shared library dllthreads
Reason: dlopen(/opt/local/lib/ocaml/stublibs/dllthreads.so, 10): Symbol not found: _caml_stop_stack_overflow_detection
  Referenced from: /opt/local/lib/ocaml/stublibs/dllthreads.so
  Expected in: flat namespace
 in /opt/local/lib/ocaml/stublibs/dllthreads.so
Abort trap: 6
```

**Comment by cooljeanius** [comment]
> ```
> nieder $ coqc.byte --help
> Usage: coqc <options> file...
> 
> Coq options are:
>   -I dir                 look for ML files in dir
>   -include dir           (idem)
> ...
> ```
> 
> That library belongs to the ocaml package.
> 
> Do you have macports installed in /opt/local?

Oh yeah derp, never mind, disregard then.

**Comment by cooljeanius** [comment]
If a review from someone else is still needed, I guess the history shows that @akhansen has also touched it in the past?

**Comment by nieder** [comment]
Let's merge this.

**Pull request merged**
