### PR TITLE
Crypt::OpenSSL::* updates

### PR DESCRIPTION
**Pull request by dmacks**
New versions, with migration to openssl110.

### CODE REVIEW

**Comment by dmacks** [comment]
I can't find a git account for maintainer Keith Ward

**Comment by nieder** [comment]
This is his SF.net profile: https://sourceforge.net/u/keithward/profile/
So keithward@users.sourceforge.net might work if his listed chaos-realm.net email doesn't work anymore.

**Comment by dmacks** [comment]
Thanks. That users.sf address bounced (500 unknown user). Will wait a week to see if the $Maintainer address elicits a response.

**Comment by KeithWard** [comment]
@nieder Hey, it looks like my email replies aren't making it through so I've gone ahead and added a review here, changes look fine.

**Comment by nieder** [comment]
To post something from @KeithWard that he sent me directly, he fixed a problem with email on his SF account, which may have been why things didn't get through earlier. But now we know his account here, so good for the future.

**Pull request merged**
