### PR TITLE
nut: 2.8.0, which is new libversions

### PR DESCRIPTION
**Pull request by dmacks**
This bumps nut to 2.8.0 (clearing an item from #863), and retains the older 2.7.4 at a new .info filename. There are several component -shlibs packages whose install_name jumped, so this preserves the older ones for whatever external packages might use them. But I have no objection to just killing off the old suite altogether. Are there any dependants other than nut itself?

### CODE REVIEW

**Comment by nieder** [comment]
nut-2.7.4.info calls `nut-2.7.4-openss110.patch`, but it is using openssl300.

**Comment by dmacks** [comment]
> nut-2.7.4.info calls `nut-2.7.4-openss110.patch`, but it is using openssl300.

Isn't that crazy? It's a 110+ compatibility patch; 300 retains the legacy interfacy (though IIRC there are compile-time warnings that it's an old API...really is 110ish in content). Better to rename it just "...openssl.patch"?

**Comment by nieder** [comment]
rename is probably nicer (or a DescPackaging note that it's using the 110 API from 300).

**Comment by nieder** [comment]
@clepple ping

**Comment by clepple** [comment]
TBH I'm probably going to have to give up maintainership of my packages because I can't seem to find time to debug the Fink installations here, let alone track the complexities of recent NUT and OpenSSL upstream. All of these changes sound good in principle, but I can't test them.

**Comment by nieder** [comment]
@dmacks these look fine but untested locally. If they built for you go ahead since it almost helps close up #863

**Review by nieder — APPROVED** [review]
LGTM

**Pull request merged**
