### PR TITLE
bump mcostabel packages to gcc9

### PR DESCRIPTION
**Pull request by nieder**
Bumps mcostabel packages from gcc5 to gcc9 for #481 
Meep is still outstanding (to v1.12.0) because meep-mpi fails looking for symbol `___ieee_divdc3` and statically linked meep errors in the build with duplicate symbols. Changing to a shared library will either require splitoffs or a private dylib.

### CODE REVIEW

**Comment by dmacks** [comment]
Changes to some static libs probably require propagating versioned BDep on their reverse-depends. See #546

**Comment by nieder** [comment]
Ugh. I completely missed #546 and #243 when doing this. I was aiming at keeping packages as close to possible as original layout.
Will let @costabel decide which way to go.

**Comment by dmacks** [comment]
We've been waiting 2 months here and almost 4 months on the other solution. @costabel, do you have any thoughts here, or @nieder is it time to push (maybe you could test-build #546)?

**Comment by costabel** [comment]
On 17/04/20 17:49, Daniel Macks wrote:
> We've been waiting 2 months here and almost 4 months on the other
> solution. @costabel <https://github.com/costabel>, do you have any
> thoughts here, or @nieder <https://github.com/nieder> is it time to push
> (maybe you could test-build #546
> <https://github.com/fink/fink-distributions/pull/546>)?

Builds OK for me and seems to run, although I haven't really done any
tests. Please go ahead.

-- 
Martin

**Comment by nieder** [comment]
Can @costabel or @dmacks carry forward the previous approval ? I added commits for harminv and libctl to sync the recent commits in master from #546 and that killed the old approval. No other changes.

**Comment by dmacks** [comment]
This PR is getting confusing, with one of its major sets of changes being abandoned and an alternative being merged from master. That's gonna be confusing when this branch gets merged. If I'm reading correctly, what is left is:
- 77748d99fb349915614131d7b05170e6096928af (ddscat, melina)
- ef77f6f32a3703bb03536aa277830d6ed0fd8a0e (modulef)
Maybe open a new PR just for that set? Or else, "those specific changes look fine to me"--cherry-pick them?

**Comment by costabel** [comment]
On 22/04/20 07:26, Daniel Macks wrote:
> This PR is getting confusing, with one of its major sets of changes
> being abandoned and an alternative being merged from master. That's
> gonna be confusing when this branch gets merged. If I'm reading
> correctly, what is left is:
> 
>   * 77748d9
>     <https://github.com/fink/fink-distributions/commit/77748d99fb349915614131d7b05170e6096928af>
>     (ddscat, melina)
>   * ef77f6f
>     <https://github.com/fink/fink-distributions/commit/ef77f6f32a3703bb03536aa277830d6ed0fd8a0e>
>     (modulef)
>     Maybe open a new PR just for that set? Or else, "those specific
>     changes look fine to me"--cherry-pick them?

I hope it wasn't me who did something wrong with git (which is still
largely mysterious for me). I tested meep and its dependencies from the
nanocomp-update branch, found that it was OK, and thought it would be
merged into master. But that was #546, not clear to me what its relation
to #569 is.

For ddscat, I have just made locally an updated version with gcc9 that
seems to work. Should I make a PR for that (provided I can find out how
to do this)?

As for melina and modulef, they are now only of archeological interest;
I think they can safely be removed from current Fink.

-- 
Martin

**Comment by nieder** [comment]
History:
#546 updated meep related programs to a more modern package layout (shared libs and also updated them to gcc9). #569 (this) updated all @costabel packages to gcc9 but didn't do any packaging changes (I created #569 without realizing #546 was around). After #546 was merged, I updated this branch to match master by copying the latest layout files for harminv and libctl so that it could be merged cleanly.

@dmacks is right. The only original changes left are in 77748d9 and ef77f6f (ddscat, melina, modulef).

If we want to clean things, then yes, a new PR would do it. It could include your ddscat update as well as removing melina and modulef.

This is my cheat sheet for making changes to my local fork and making a new Pull Request.
https://github.com/fink/fink-distributions/wiki/Submitting-new-or-updated-packages

I can help as well with any questions that might pop up.

**Comment by costabel** [comment]
On 22/04/20 11:59, nieder wrote:
> If we want to clean things, then yes, a new PR would do it. It could
> include your ddscat update as well as removing melina and modulef.

OK, I did it (at least, I did something; this git stuff is still scary).

-- 
Martin

**Comment by nieder** [comment]
@costabel your git stuff was fine. You can delete your branch (both local copy and on your remote fork) if you want.

**Comment by nieder** [comment]
Issue dealt with in #606

**Pull request closed without merging**
