### PR TITLE
fix numpy.distutils and SHELL issue (#121)

### PR DESCRIPTION
**Pull request by nieder**
Fixes the problem with the environment SHELL from fink-bld (/usr/bin/false) not being a real shell.

### CODE REVIEW

**Comment by dmacks** [comment]
Could you document in numpy-py.info itself why the special version-dependency on numpy-py? Otherwise lgtm. matplotlib-basemap-py.info could also benefit from that tweak.

**Comment by dhomeier** [comment]
Same for cython-py.info and my numba-py submission #207 (I could take care of that of course).
Alternatively I had thought about a patch that will first check if `$SHELL` is a functioning shell and only afterwards revert to `/bin/sh`; something like
```
        sh = os.environ.get('SHELL', '/bin/sh')
        if subprocess.run([sh, '-c', 'exit 0'], timeout=100).returncode != 0:
            sh = '/bin/sh'
```
would of course not change anything for the fink builds, but restore the original behaviour in the (remote?) case a user wants to build some extension using `numpy.distutils` with their own `$SHELL`. It's still not clear to me if that would be POSIX-compliant, so might not be worth the hassle...

**Comment by nieder** [comment]
matplotlib-basemap-py and mayavi2-py (@costabel) now also patched to build.

**Comment by dmacks** [comment]
@dhomeier, upstream numpy has a ticket where they are discussing various solutions. Feel free to join them at numpy/numpy/issues/9970

**Comment by nieder** [comment]
Pushing since it cleans up an issue that propagates as FTBFS for several packages.

**Comment by dmacks** [comment]
Upstream switched to handling it in numpy/numpy/issues/11824

**Pull request merged**
