### PR TITLE
Add a new CRAN package vctrs

### PR DESCRIPTION
**Pull request by babayoshihiko**
New packages vctrs and zeallot.

### CODE REVIEW

**Comment by nieder** [comment]
````
Reading dependency for cran-vctrs-r33-0.2.0-1...
Can't resolve dependency "cran-ellipsis-r33 (>= 0.2.0)" for package "cran-vctrs-r33-0.2.0-1"
(no matching packages/versions found)
Exiting with failure.
````

**Comment by babayoshihiko** [comment]
> Reading dependency for cran-vctrs-r33-0.2.0-1...
> Can't resolve dependency "cran-ellipsis-r33 (>= 0.2.0)" for package "cran-vctrs-r33-0.2.0-1"
> (no matching packages/versions found)
> Exiting with failure.

cran-ellipsis-r33 has been updated.

**Comment by nieder** [comment]
```
Warning: Description of "cran-zeallot-r35" exceeds 45 characters. (cran-zeallot-r.info)
```

Changing to `Multiple/Unpacking/Destructuring Assignment` decreases the character count to 43.

**Comment by nieder** [comment]
Otherwise OK with that change.

**Comment by babayoshihiko** [comment]
Changed to Multiple/Unpacking/Destructuring Assignment

**Pull request merged**
