### PR TITLE
Ghostscript 9.53.3 and Freetype 2.10.4

### PR DESCRIPTION
**Pull request by PovlAbrahamsen**
Here are updated packages for Freetype 2.10.2, and Ghostscript 9.52 (which depends on Freetype 2.10 and jbig2dec 0.16 or higher). So this pull request depends on #596

### CODE REVIEW

**Comment by PovlAbrahamsen** [comment]
These have been tested on 10.15.6, and build with "-m"

**Comment by dmacks** [comment]
Thanks for working on these (especially ft219)! I see you commented-out a ton of patches. If they're no longer relevant, such as CVE and no-uninitialized-bbox.patch that are now in the newer upstream version, can just delete the lines altogether. But some of them still seem relevant. Debian still has enable-gxvalid-otvalid.patch and enable-subpixel-rendering.patch in their 2.10.2 package (https://sources.debian.org/src/freetype/2.10.2+dfsg-3/debian/patches/). And the t1tables.h part of our own .patch is an ABI compatibility fix that seems still relevant for its documented purpose (I did not look closely at the ABI/API to make sure there were no other regressions recently).

**Comment by PovlAbrahamsen** [comment]
Thanks for the comments. I'll take a closer look over the weekend, and update the PR. I did try to find Debian patches for this version, but must have been looking in the wrong location.

**Comment by PovlAbrahamsen** [comment]
I have now applied the ABI fix, and the relevant Debian patches. Quite a few apply to documentation that we aren't installing anyway.

**Comment by PovlAbrahamsen** [comment]
I've just spotted that Ghostscript 9.53.1 was released five days ago. Looks like a trivial update from 9.52, but does require jbig2dec 0.19. If you want, I can update the package descriptions. Note that #596 has been waiting for a response from the maintainer for five months now...

**Comment by PovlAbrahamsen** [comment]
Bump for review... @dmacks @nieder

**Comment by PovlAbrahamsen** [comment]
Bumped to freetype 2.10.4, with same Debian patches applied as before (except the CVE for 2.10.2, which was incorporated upstream). Also added depend for libbrotli1.

**Comment by dmacks** [comment]
There's a bug in the existing package, may as well fix it now: need --without-harfbuzz because there is no BDep for it but it gets autodetected if present, so the actual binary library is uncontrolled. We need to disable that optional feature (as does debian, rather than add deps) to prevent a circular dependency: libharfbuzz has non-optional dependency on freetype219. Otherwise that pkg looks good.

**Comment by PovlAbrahamsen** [comment]
"--without-harfbuzz" has been added to the configure parameters.

**Comment by dmacks** [comment]
freetype219 looks great. Building ghostscript I see:
```
checking for dbus with pkg-config... yes
```
but no dependencies on the dbus packages. But then build-fail (I'm on 10.13):
```
gcc  -DHAVE_MKSTEMP  -DHAVE_FSEEKO  -DHAVE_FONTCONFIG -DHAVE_LIBIDN -DHAVE_SETLOCALE -DHAVE_SSE2 -DHAVE_DBUS -DHAVE_BSWAP32  -DHAVE_STRERROR -DHAVE_ISNAN -DHAVE_ISINF  -DHAVE_PREAD_PWRITE=1 -DGS_RECURSIVE_MUTEXATTR=PTHREAD_MUTEX_RECURSIVE -O2 -DNDEBUG -MD -Wno-shift-negative-value -I/sw/include  -Wall -Wstrict-prototypes -Wundef -Wmissing-declarations -Wmissing-prototypes -Wwrite-strings -fno-strict-aliasing -Werror=declaration-after-statement -fno-builtin -fno-common -Werror=return-type -DHAVE_STDINT_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBDL=1 -DGX_COLOR_INDEX_TYPE="unsigned long long" -D__USE_UNIX98=1   -DHAVE_RESTRICT=1 -DUSE_LIBICONV_GNU -DUSE_LIBPAPER -I/sw/include -fno-strict-aliasing -DHAVE_POPEN_PROTO=1    -I./obj -I./base -I./devices  -DWHICH_CMS="lcms2mt" -DHAVE_RESTRICT=1 -DUSE_LIBICONV_GNU -DUSE_LIBPAPER -I/sw/include/freetype2 -DSHARE_FT=1 -o ./obj/fapi_ft_1.o -c ./base/fapi_ft.c
./base/fapi_ft.c:129:1: error: expected function body after function declarator
FF_alloc(FT_Memory memory, long size)
^
./base/fapi_ft.c:236:34: error: use of undeclared identifier 'file_default_buffer_size'
                                 file_default_buffer_size, &ps, pfn.iodev,
                                 ^
./base/fapi_ft.c:259:20: error: use of undeclared identifier 'FF_stream_read'
    ftstrm->read = FF_stream_read;
                   ^
./base/fapi_ft.c:260:21: error: use of undeclared identifier 'FF_stream_close'
    ftstrm->close = FF_stream_close;
                    ^
./base/fapi_ft.c:282:33: warning: implicit declaration of function 'FF_alloc' is invalid in C99 [-Wimplicit-function-declaration]
    ff_face *face = (ff_face *) FF_alloc(s->ftmemory, sizeof(ff_face));
                                ^
./base/fapi_ft.c:282:33: warning: this function declaration is not a prototype [-Wstrict-prototypes]
./base/fapi_ft.c:282:21: warning: cast to 'ff_face *' (aka 'struct ff_face_s *') from smaller integer type 'int' [-Wint-to-pointer-cast]
    ff_face *face = (ff_face *) FF_alloc(s->ftmemory, sizeof(ff_face));
                    ^
./base/fapi_ft.c:314:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, a_face->ft_inc_int);
        ^
./base/fapi_ft.c:314:9: warning: this function declaration is not a prototype [-Wstrict-prototypes]
./base/fapi_ft.c:330:31: warning: implicit declaration of function 'FF_alloc' is invalid in C99 [-Wimplicit-function-declaration]
        (FT_IncrementalRec *) FF_alloc(s->ftmemory,
                              ^
./base/fapi_ft.c:330:9: warning: cast to 'FT_IncrementalRec *' (aka 'struct FT_IncrementalRec_ *') from smaller integer type 'int' [-Wint-to-pointer-cast]
        (FT_IncrementalRec *) FF_alloc(s->ftmemory,
        ^
./base/fapi_ft.c:350:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, a_inc_int_info->glyph_data);
        ^
./base/fapi_ft.c:501:41: warning: implicit declaration of function 'FF_alloc' is invalid in C99 [-Wimplicit-function-declaration]
        (FT_Incremental_InterfaceRec *) FF_alloc(s->ftmemory,
                                        ^
./base/fapi_ft.c:501:9: warning: cast to 'FT_Incremental_InterfaceRec *' (aka 'struct FT_Incremental_InterfaceRec_ *') from smaller integer type 'int' [-Wint-to-pointer-cast]
        (FT_Incremental_InterfaceRec *) FF_alloc(s->ftmemory,
        ^
./base/fapi_ft.c:509:13: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
            FF_free(s->ftmemory, i);
            ^
./base/fapi_ft.c:524:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, a_inc_int);
        ^
./base/fapi_ft.c:572:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->bitmap_glyph);
        ^
./base/fapi_ft.c:577:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->outline_glyph);
        ^
./base/fapi_ft.c:825:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_free(s->ftmemory, bmg);
                    ^
./base/fapi_ft.c:834:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_free(s->ftmemory, olg);
                    ^
./base/fapi_ft.c:927:26: error: use of undeclared identifier 'FF_alloc'; did you mean 's_alloc'?
    s->ftmemory->alloc = FF_alloc;
                         ^~~~~~~~
                         s_alloc
./base/stream.h:327:9: note: 's_alloc' declared here
stream *s_alloc(gs_memory_t *, client_name_t);
        ^
./base/fapi_ft.c:927:24: warning: incompatible pointer types assigning to 'FT_Alloc_Func' (aka 'void *(*)(struct FT_MemoryRec_ *, long)') from 'stream *(gs_memory_t *, client_name_t)' (aka 'struct stream_s *(struct gs_memory_s *, const char *)') [-Wincompatible-pointer-types]
    s->ftmemory->alloc = FF_alloc;
                       ^ ~~~~~~~~
./base/fapi_ft.c:928:25: error: use of undeclared identifier 'FF_free'
    s->ftmemory->free = FF_free;
                        ^
./base/fapi_ft.c:929:28: error: use of undeclared identifier 'FF_realloc'; did you mean 'realloc'?
    s->ftmemory->realloc = FF_realloc;
                           ^~~~~~~~~~
                           realloc
/usr/include/stdlib.h:168:7: note: 'realloc' declared here
void    *realloc(void *__ptr, size_t __size) __result_use_check __alloc_size(2);
         ^
./base/fapi_ft.c:929:26: warning: incompatible pointer types assigning to 'FT_Realloc_Func' (aka 'void *(*)(struct FT_MemoryRec_ *, long, long, void *)') from 'void *(void *, size_t)' (aka 'void *(void *, unsigned long)') [-Wincompatible-pointer-types]
    s->ftmemory->realloc = FF_realloc;
                         ^ ~~~~~~~~~~
./base/fapi_ft.c:1123:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->bitmap_glyph);
        ^
./base/fapi_ft.c:1128:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->outline_glyph);
        ^
./base/fapi_ft.c:1237:21: warning: implicit declaration of function 'FF_alloc' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_alloc(s->ftmemory, length);
                    ^
./base/fapi_ft.c:1236:55: warning: incompatible integer to pointer conversion assigning to 'unsigned char *' from 'int' [-Wint-conversion]
                open_args.memory_base = own_font_data =
                                                      ^
./base/fapi_ft.c:1253:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_free(s->ftmemory, own_font_data);
                    ^
./base/fapi_ft.c:1273:21: warning: implicit declaration of function 'FF_alloc' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_alloc(s->ftmemory, open_args.memory_size);
                    ^
./base/fapi_ft.c:1272:55: warning: incompatible integer to pointer conversion assigning to 'unsigned char *' from 'int' [-Wint-conversion]
                open_args.memory_base = own_font_data =
                                                      ^
./base/fapi_ft.c:1287:21: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                    FF_free(s->ftmemory, own_font_data);
                    ^
./base/fapi_ft.c:1305:17: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                FF_free(s->ftmemory, own_font_data);
                ^
./base/fapi_ft.c:1315:17: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
                FF_free(s->ftmemory, own_font_data);
                ^
./base/fapi_ft.c:1762:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->outline_glyph);
        ^
./base/fapi_ft.c:1767:9: warning: implicit declaration of function 'FF_free' is invalid in C99 [-Wimplicit-function-declaration]
        FF_free(s->ftmemory, s->bitmap_glyph);
        ^
30 warnings and 7 errors generated.
```
There is a flaw in the -I ordering (global before local), but even if I manually run that command with the correct ordering, the same results.

**Comment by dmacks** [comment]
The gs error due to a backward-incompatible change (removal of some #define) in the new ft. See:

https://bugs.ghostscript.com/show_bug.cgi?id=702985

That bug-report has a link to the fix in gs (debian does this in their gs package). Applying that gets me going again. But I wonder if we should fix this in ft?

**Comment by PovlAbrahamsen** [comment]
I've applied the patch to Ghostscript. If Freetype hasn't yet reinstated this macro, we may as well assume that it will be missing in the future. I've also removed "UseMaxBuildJobs: false" from Ghostscript; it seems to build just fine without it.

Although configure does check for dbus and sets a flag "-DHAVE_DBUS", this appears to be a vestige of previous versions, and isn't actually used anywhere in the code. So no need for depends/builddepends.

Happy New Year!

**Review by dmacks — APPROVED** [review]
ft upstream has explicitly declined to re-supply that macro, so I think we're best following other distros' lead and fixing gs's use of it. Our vtk5.8 builds cleanly and our vtk5.10 fails for other reasons, so I don't think there's anything more that needs to happen for now. 

Once I finish tracing it, I'll add some Desc notes and links, but no need to wait here.

**Pull request merged**
