### PR TITLE
htodd-10.14.5-perl: Add 5.18.4 to perlmods.

### PR DESCRIPTION
**Pull request by htodd**
Adding 5.18.4 to perlmods of files I'm using.

### CODE REVIEW

**Comment by nieder** [comment]
This depends on #423 and fink/fink#190.

**Comment by htodd** [comment]
I'll do some more validation and fix those info files.

**Comment by htodd** [comment]
Building with -Kk made me touch a bunch more files. Please check this for me.

**Comment by htodd** [comment]
I give up. I'll delete this branch. You fix it.

**Pull request closed without merging**
