### PR TITLE
Update perlmods

### PR DESCRIPTION
**Pull request by nieder**
updates to some perlmods.
Moose fix for issue #127 is here (version update and update some deps)
@jessealama has a couple packages here too

### CODE REVIEW

**Comment by nieder** [comment]
module-build-tiny-pmXXX is not needed anymore for class::load.

In my local branch, how do I fix the devel::stacktrace conflict? Do I make a commit that generates a file identical to the unvarianted one you checked in?

**Comment by dmacks** [comment]
For pathtools-pm.info, it would be good to retain some sort of license statement in DocFiles. You could use the PatchScript one-liner from statistics-shannon-pm.info to extract it from the main .pm POD.

**Comment by nieder** [comment]
bah. Using github's webbased conflict resolution adds changes from Master to the branch. Just waiting if @jessealama has any comments.

**Comment by jessealama** [comment]
I took a look -- nothing weird stood out to my eyes, so I think this can be merged.

**Pull request merged**
