### PR TITLE
Vim: Welcome to Vim-8.1.2291.

### PR DESCRIPTION
**Pull request by htodd**
Only tested vim-nox on Catalina.

### CODE REVIEW

**Comment by nieder** [comment]
Needs libiconv-dev to not use /usr/include/iconv.h, and newer versions apparently check for and use libcanberra0.

**Comment by htodd** [comment]
Newer versions of what?

On Tue, 12 Nov 2019, nieder wrote:

> 
> Needs libiconv-dev to not use /usr/include/iconv.h, and newer versions apparently check for and use libcanberra0.
> 
> ?
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE477M22PS5ZEAXOFB3DQTJ4MTA5CNFSM4JLUOHH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDZVV6Q.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by nieder** [comment]
Of vim. 8.1.2120 and 8.1.2238 both use libcanberra0 if present.

**Comment by htodd** [comment]
Well, if it's broken now, it was broken before. I may just push anyway.

**Comment by dmacks** [comment]
I can hack on the DFU/gtk bits sometime hopefully soon. I guess up to you whether you want to commit "new version, not worse" or wait until "now-known issues are fixed".

**Comment by htodd** [comment]
I can wait. No one has really asked me for a new vim for a long time.

On Tue, 12 Nov 2019, Daniel Macks wrote:

> 
> I can hack on the DFU/gtk bits sometime hopefully soon. I guess up to you whether you want to commit "new version, not worse" or
> wait until "now-known issues are fixed".
> 
> ?
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE4YB23GLDQDLB3ETXTLQTOB35A5CNFSM4JLUOHH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED44AUY.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by dhomeier** [comment]
> I can wait. No one has really asked me for a new vim for a long time.

I am sure the regular version updates are much appreciated nonetheless!
I was not able to download the sources for the latest version added to master, however - neither as `vim-8.2.012.tar.bz2`nor `vim-8.2.0012.tar.bz2`; is that put on hold now until this issue is resolved?
Experimenting with the [GitHub source](https://github.com/vim/vim/archive/v8.2.0012.tar.gz) I could not get the `make install DESTDIR=%d` variant in any way to install to the correct path, so the alternative suggested by @dmacks seems to be the better option – adding  to the `configure` flags
`--disable-icon-cache-update --disable-desktop-database-update`
Then the Post*Scripts as e.g. adapted from devel/devhelp.info should probably do the job.

I also noted that the `--enable-pythoninterp` config flag is linking to the system (Framework) Python, but am not sure if that is problematic, and could not figure out how to point the build to Fink's `python2.7` instead anyway (there is a `--with-python-config-dir=PATH` flag, but it is marked deprecated).

**Comment by htodd** [comment]
Whoops. I uploaded the tarball.

I'm unable to test the non-nox version of Vim because gtk2 is broken on
Catalina. I modified the info file a bit and I'll see if I can find an
older system to test it on.

On Wed, 18 Dec 2019, Derek Homeier wrote:

>
>       I can wait. No one has really asked me for a new vim for a long time.
> 
> I am sure the regular version updates are much appreciated nonetheless!
> I was not able to download the sources for the latest version added to master, however - neither as vim-8.2.012.tar.bz2nor
> vim-8.2.0012.tar.bz2; is that put on hold now until this issue is resolved?
> Experimenting with the GitHub source I could not get the make install DESTDIR=%d variant in any way to install to the correct
> path, so the alternative suggested by @dmacks seems to be the better option ? adding to the configure flags
> --disable-icon-cache-update --disable-desktop-database-update
> Then the Post*Scripts as e.g. adapted from devel/devhelp.info should probably do the job.
> 
> I also noted that the --enable-pythoninterp config flag is linking to the system (Framework) Python, but am not sure if that is
> problematic, and could not figure out how to point the build to Fink's python2.7 instead anyway (there is a
> --with-python-config-dir=PATH flag, but it is marked deprecated).

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by dhomeier** [comment]
I managed to test both variants on 10.12 with these changes to the scripts:
```
CompileScript: <<
        #!/bin/sh -ev
        cd src
        if [ "%type_raw[-nox]" == "." ]; then
                ./configure --prefix=%p --with-gnome=%p --mandir=%i/share/man --enable-cscope --enable-multibyte --with-features=big --enable-gui=gtk2 --disable-darwin --disable-icon-cache-update --disable-desktop-database-update --with-local-dir=%p --enable-pythoninterp --enable-python3interp
        fi
        if [ "%type_raw[-nox]" == "-nox" ]; then
                ./configure --prefix=%p --mandir=%i/share/man --enable-cscope --enable-multibyte --with-features=big --disable-gui --disable-darwin --disable-icon-cache-update --disable-desktop-database-update --without-x --with-local-dir=%p --enable-pythoninterp --enable-python3interp
        fi
        make
        fink-package-precedence --depfile-ext='\.d' .
<<
InstallScript: <<
        make install prefix=%i
        perl -pi -e 's,%i,%p,g' %i/share/man/man1/*
<<

InfoTest: <<
        UseMaxBuildJobs: false
        Testscript: <<
                #!/bin/sh -ev
                cd src
                make run_json_test run_kword_test run_memfile_test run_message_test unittest
        <<

PostInstScript: <<
        [ "%type_raw[-nox]" == "." -a -x %p/bin/update-desktop-database ] && update-desktop-database -q || :
        [ "%type_raw[-nox]" == "." ] && gtk-update-icon-cache -f -t %p/share/icons/hicolor || :
<<

PostRmScript: <<
        [ "%type_raw[-nox]" == "." -a -x %p/bin/update-desktop-database ] && update-desktop-database -q || :
        [ "%type_raw[-nox]" == "." ] && gtk-update-icon-cache -f -t %p/share/icons/hicolor || 
<<
```
I added the `--enable-python3interp` flag as an experiment, but keeping this would of course require adding one of the `python3x` as dependency, at least on older OS versions.
The test for `%p/bin/update-desktop-database` in the Post*Scripts is perhaps redundant, as this should be installed with the new `desktop-file-utils` `RuntimeDepends`.
As you see I also tried to reinstate the test script, but could not run the full suite since the `scripttests` part is failing early on with a (to me) nondescriptive error.

**Comment by dmacks** [comment]
@htodd pushed 8.2.012 to master (definitely nice to keep new versions available!), but this PR seems like a good place to keep discussing improvements...

--disable-canberra turns off that feature (sound support), which has glib2 as one of its internal deps. Is that the level at which Catalina is a problem, or only at the GTK gui toolbox? 

There's a lot of redundancy in the CompileScript that makes it hard to see what is specific to the different variants. Consider instead using ConfigureParams, which supports the same varianting syntax as the dependency fields:
```
ConfigureParams: <<
        (%type_raw[-nox] = .) --with-gnome=%p \
        (%type_raw[-nox] = -nox) --disable-gui \
        (%type_raw[-nox] = -nox) --without-x \
        --mandir=%i/share/man \
        --enable-cscope \
        --enable-multibyte \
        --with-features=big \
        --enable-gui=gtk2 \
        --disable-darwin \
        --with-local-dir=%p \
        --enable-pythoninterp
<<
CompileScript: <<
        #!/bin/sh -ev
        cd src
        %{default_script}
        fink-package-precedence --depfile-ext='\.d' .
<<
```

@dhomeier, what was the problem you had with ```make install DESTDIR=%d```? Using that would also avoid needing to pass --mandir at all. With that pair of changes I got equivalent .deb results on 10.13. Still need the perl-pie (even now, with use of the default InstallScript), as dhomeier proposed.

**Comment by htodd** [comment]
OK, I think I got @dmacks changes in.

**Comment by dhomeier** [comment]
> @dhomeier, what was the problem you had with `make install DESTDIR=%d`? Using that would also avoid needing to pass --mandir at all. With that pair of changes I got equivalent .deb results on 10.13. Still need the perl-pie (even now, with use of the default InstallScript), as dhomeier proposed.

I had the `--mandir=%i/share/man` flag left in place, which installed the manpages somewhere under `%d/%i`...
After removing the above from `ConfigureParams` `make install DESTDIR=%d` installed the manual to a valid path, and with the correct paths in the manpages without needing the perl-pie any more.

**Comment by dmacks** [comment]
Some of those PostInst/PostRm pieces are not needed. There is no gconf schema file, so the current vim-8.2.111-1 in stable fails to install:
```
Setting up vim (8.2.111-1) ...
I/O warning : failed to load external entity "/sw/etc/gconf/schemas/devhelp.schemas"
Failed to open `/sw/etc/gconf/schemas/devhelp.schemas': No such file or directory
/sw/bin/dpkg: error processing vim (--install):
 subprocess post-installation script returned error exit status 1
Errors were encountered while processing:
 vim
```

There is also no share/mime file, so the update-mime-database calls are not needed.

In order to support update-desktop-database and gtk-update-icon-cache, the package needs Depends for desktop-file-utils and gtk+2 (not just gtk+2-shlibs).

**Comment by htodd** [comment]
I think I fixed it but I can't find it on github any more.

On Tue, 14 Jan 2020, Daniel Macks wrote:

> 
> Some of those PostInst/PostRm pieces are not needed. There is no gconf schema file, so the current vim-8.2.111-1 in stable fails
> to install:
> 
> Setting up vim (8.2.111-1) ...
> I/O warning : failed to load external entity "/sw/etc/gconf/schemas/devhelp.schemas"
> Failed to open `/sw/etc/gconf/schemas/devhelp.schemas': No such file or directory
> /sw/bin/dpkg: error processing vim (--install):
>  subprocess post-installation script returned error exit status 1
> Errors were encountered while processing:
>  vim
> 
> There is also no share/mime file, so the update-mime-database calls are not needed.
> 
> In order to support update-desktop-database and gtk-update-icon-cache, the package needs Depends for desktop-file-utils and
> gtk+2 (not just gtk+2-shlibs).
> 
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE47TB6YPU2BZN5XP3JDQ5Z4URA5CNFSM4JLUOHH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI64S7A.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by dhomeier** [comment]
> I think I fixed it but I can't find it on github any more.

These were the fields I used with your `ConfigureParams` and `CompileScript` for successful build on 10.12, if it's of any help:
```
InstallScript: <<
        make install DESTDIR=%d
<<

InfoTest: <<
        UseMaxBuildJobs: false
        Testscript: <<
                #!/bin/sh -ev
                cd src
                make scripttests || echo fail
                make run_json_test run_kword_test run_memfile_test run_message_test unittest
        <<
<<

PostInstScript: <<
        [ "%type_raw[-nox]" == "." -a -x %p/bin/update-desktop-database ] && update-desktop-database -q || :
        [ "%type_raw[-nox]" == "." ] && gtk-update-icon-cache -f -t %p/share/icons/hicolor || :
<<

PostRmScript: <<
        [ "%type_raw[-nox]" == "." -a -x %p/bin/update-desktop-database ] && update-desktop-database -q || :
        [ "%type_raw[-nox]" == "." ] && gtk-update-icon-cache -f -t %p/share/icons/hicolor || :
<<
```

**Comment by htodd** [comment]
I give up on this GitHub thing.

**Pull request closed without merging**
