### PR TITLE
Coot version update

### PR DESCRIPTION
**Pull request by wgscott**
I hope I have done this correctly.

### CODE REVIEW

**Comment by nieder** [comment]
You don't need to merge your own branch (wgscott-patch-1) that you did your changes in back to your own master before doing a pull request off your master branch. It's probably preferable to just to the pull request off your changes branch.

**Comment by nieder** [comment]
Can coot be updated to use the fftw3 and boost1.63 packages?

**Comment by wgscott** [comment]
Currently, no on the fftw3.

I can try to get it to work with the more current boost package (I haven’t tried). It will be a few weeks before I have time to try.

Bill

**Comment by wgscott** [comment]
coot now builds with latest boost.  rdkit (coot dependency) update and now builds with latest boost.  refmac (coot dependency) has fixed md5sum

**Comment by nieder** [comment]
### In rdkit:
~~~~
Warning: Malformed dependency "1.0.0 %n  (>= 2017.09.1-1)" for "%p/lib/%N/libRDKitRGroupDecomposition.1.dylib" in field "shlibs" of "splitoff". (rdkit.info)
Warning: Malformed dependency "1.0.0 %n  (>= 2017.09.1-1)" for "%p/lib/%N/libRDKitStructChecker.1.dylib" in field "shlibs" of "splitoff". (rdkit.info)
Warning: Malformed dependency "1.0.0 %n  (>= 2017.09.1-1)" for "%p/lib/%N/libRDKitSubstructLibrary.1.dylib" in field "shlibs" of "splitoff". (rdkit.info)
Warning: Malformed dependency "1.0.0 %n  (>= 2017.09.1-1)" for "%p/lib/%N/libRDKitTrajectory.1.dylib" in field "shlibs" of "splitoff". (rdkit.info)
~~~~
You have an extra `1.0.0` in the Shlibs: field for those four dylibs.

Suggestion for future releases (not needed now):
The new rdkit tarball is called `Release_2017_09_3.tar.gz`. Instead of using `SourceDirectory` to get Fink to find the extracted dir, might want to use `SourceRename` to change the tarball name to rdkit-Release-2017_09_3.tar.gz. The end result is the same, but using `SourceRename` helps point to which package the tarball belongs to. 

### In coot:
The dylibs link as flat_namespace. If that's necessary, would be good to have a note about it in DescPackaging.

**Comment by wgscott** [comment]
Fixed two files

**Pull request merged**
