### PR TITLE
Netcdf updates: netcdf-c18 4.7.4, netcdf-cxx4 4.3.1, netcdf-fortran8 4.5.3, nco 4.9.5, ncview 2.1.7

### PR DESCRIPTION
**Pull request by PovlAbrahamsen**
Here are a bunch of NetCDF updates:

1. netcdf-c18 version 4.7.4 - latest upstream version.
   - updated other netcdf packages to conflict/replace netcdf-c18. Revisions not bumped.
   - only packaging change from before is to remove private library libh5bzip2.so. This had previously been called libbzip2.so, and there was code in the previous infofile to delete it before packaging. In netcdf-c15 this was installed, without listing it as a private library in the shlibs section. If anyone feels strongly that this will be used by anyone in the future, it can be included and declared. This has previously been discussed at Unidata/netcdf-c#1348 
2. netcdf-cxx4 4.3.1 - latest upstream version.
   - update source path to download from Github
   - remove installation of libh5bzip2.so from this one, too! See Unidata/netcdf-cxx4#75
   - generally, the build chain for this library is a bit of a mess (not our fault, upstream; see, e.g. Unidata/netcdf-cxx4#73, Unidata/netcdf-cxx4#87). Note that HDF5 is required during compile/test time, but not linked directly to this library. It is, however, a dependency of netcdf-c18-shlibs, which in turn is a dependency of this library.
3. netcdf-fortran8 4.5.3 - latest upstream version
4. nco 4.9.5 - latest upstream version.
   - changed to build with netcdf-c18
   - remove patchfile, since this was fixed upstream
   - removed redundant line in patchscript
5. ncview 2.1.7
   - changed to build with netcdf-c18
   - bug fix for xcode 12: there were two implicitly declared functions

### CODE REVIEW

**Comment by nieder** [comment]
Just my checklist to keep track of things:
- [x] netcdf-c18
- [ ] netcdf-cxx4
- [ ] netcdf-fortran8
- [ ] nco
- [ ] ncview

**Review by nieder — CHANGES_REQUESTED** [review]
Looks generally good. Two packing changes:
1) You need to bump %r for the older netcdf-cXX packages. Changes to the `Conflicts/Replaces` fields are propagated into the .deb file, so a change there needs a new %r.
2) Please add a DescPort entry to ncview.info about the patch.

Ready to go in when those are done.

**Comment by PovlAbrahamsen** [comment]
Done! For netcdf-c15, I have also changed "libbzip2" to "libh5bzip2" in the InstallScript, to avoid installation of the test library (as was originally intended).

**Comment by PovlAbrahamsen** [comment]
BTW, I have also informed the author of ncview. So hopefully this will be fixed upstream at some point.

**Review by nieder — APPROVED** [review]

**Pull request merged**
