### PR TITLE
sjeng: Fix FTBFS and import unreleased upstream revisions

### PR DESCRIPTION
**Pull request by dmacks**
Permissions problem under --build-as-nobody (fink's default mode) led me down a rabbit-hole of fixing things.

### CODE REVIEW

**Comment by nieder** [comment]
With the new revision here:
````
test -z "/sw/build.build/root-sjeng-11.2-4/sw/bin" || ./install-sh -c -d "/sw/build.build/root-sjeng-11.2-4/sw/bin"
/bin/sh: ./install-sh: Permission denied
````
install-sh is 644.

**Comment by microtherion** [comment]
Very interesting. Where did this rollup patch come from?

**Comment by dmacks** [comment]
@microtherion https://github.com/gcp/sjeng/

**Comment by dmacks** [comment]
@nieder Looks like that only happens if coreutils is not detected...yeah, chmod is better than a BDep there. Fixed.

**Comment by nieder** [comment]
@microtherion : review ping

**Comment by dmacks** [comment]
@microtherion, or @nieder in their absence?

**Pull request merged**
