### PR TITLE
alpine: new upstream

### PR DESCRIPTION
**Pull request by htodd**
Alpine is a bit tricky. I got it to build but could you look it over?

### CODE REVIEW

**Comment by nieder** [comment]
* NoSourceDirectory is not needed. The tarball expands to %n-%v as expected.
* My fink-openssl certs directory is `%p/etc/ssl/certs` not `%p/etc/openssl`.  The ca-bundle package also puts its things in `%p/etc/ssl/certs`. Did the certs location parameter need to be changed? If so, please document in DescPackaging.
** Also, configure has code for detection of hardcoded `/sw/etc/ssl` with Darwin, so should probably at least patch out the literal `/sw` in there.
* There's detection of `/sw/bin/hunspell` and its location is saved inside the installed binaries. So that should be made a Depends (binary only, no the library). 
* `--prefix=%d` writes the build directory into the binaries. Does `--prefix=%p` and `make install DESTDIR=%d` not work?

**Comment by htodd** [comment]
@nieder the only thing I couldn't figure out was the `--prefix` change.

`--prefix=%p` and `make install DESTDIR=%d` do not work.

**Comment by nieder** [comment]
The screwy stuff in alpined that gets badly installed when not using `--prefix=%d` in %c is controlled by the flag `--without-tcl`. So if we don't need Web Alpine, then that should do it.

**Comment by htodd** [comment]
I don't think web alpine is building at all. I tried adding --without-tcl but it did nothing. Still no luck with your --prefix change @nieder.

**Comment by nieder** [comment]
After commit c5526b4, I get these validation errors:
```
Validating .deb dir /sw/build.build/root-alpine-2.22-1.5...
Error: File installed outside of allowable subdirectories of /sw
	Offending file: /sw/build.build/
	Offending file: /sw/build.build/alpine-2.22-1.5/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpined
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpineldap
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.a
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.dylib
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/alpine
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pico
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pilot
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpdump
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpload
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/alpine.1
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pico.1
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pilot.1
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpdump.1
	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpload.1
Error: Published libtool compiler information points to fink build dir.
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
Error: The -framework flag may get munged by libtool. See the gcc manpage for information about passing multi-word options to flags for specific compiler passes.
	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
	Offending line: inherited_linker_flags='  -framework Carbon -framework ApplicationServices -framework Security'
Error: package contains the shared library
          /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
       but the corresponding install_name and compatibility_version
          %p/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/../../lib/libwpcomm.1.dylib 2.0.0
       are not listed in the Shlibs field.  See the packaging manual.
SERIOUS WARNING: /sw/build.build/root-alpine-2.22-1.5/sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib appears to have been linked using a flat namespace.
       If this package BuildDepends on libtool2, make sure that you use
          BuildDepends: libtool2 (>= 2.4.2-4).
       and use autoreconf to regenerate the configure script.
       If the package doesn't BuildDepend on libtool2, you'll need to
       update its build procedure to avoid passing
          -Wl,-flat_namespace
       when linking libraries.

		  If this package actually requires a flat namespace build,
		  then ignore this message.

Removing runtime build-lock...
```
The following `ConfigureParams` fix all the above but lose everything related to web alpine, which we've never had anyway:
```
ConfigureParams: <<
	--disable-debug \
	--with-ssl-dir=%p \
	--with-ssl-certs-dir=%p/etc/ssl/certs \
	--with-ldap-dir=%p \
	--with-local-password-cache-method \
	--without-pubcookie \
	--without-tcl
<<
```

**Comment by nieder** [comment]
Note that you need `tcltk-dev` installed to have all that web and libwpcomm.dylib stuff built.  Which is why `--without-tcl` needs to be explicit (or the web stuff installed properly).

**Comment by htodd** [comment]
My last commit added that and changed all your suggestions back to what
I had.

On Wed, 6 May 2020, nieder wrote:

> 
> Note that you need tcltk-dev installed to have all that web and libwpcomm.dylib stuff built. Which is why --without-tcl needs to
> be explicit (or the web stuff installed properly).
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE42VNB4FWNYQWURK5NDRQH2E3A5CNFSM4MQ2FYDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEVAAAEY.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by htodd** [comment]
That's my intermediate commit. That shouldn't be what's there now.

On Wed, 6 May 2020, nieder wrote:

> 
> After commit c5526b4, I get these validation errors:
> 
> Validating .deb dir /sw/build.build/root-alpine-2.22-1.5...
> Error: File installed outside of allowable subdirectories of /sw
> 	Offending file: /sw/build.build/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpined
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpineldap
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.a
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.dylib
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/alpine
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pico
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pilot
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpdump
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpload
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/alpine.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pico.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pilot.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpdump.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpload.1
> Error: Published libtool compiler information points to fink build dir.
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> Error: The -framework flag may get munged by libtool. See the gcc manpage for information about passing multi-word options to fl
> ags for specific compiler passes.
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> 	Offending line: inherited_linker_flags='  -framework Carbon -framework ApplicationServices -framework Security'
> Error: package contains the shared library
>           /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
>        but the corresponding install_name and compatibility_version
>           %p/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/../../lib/libwpcomm.1.dylib 2.0.0
>        are not listed in the Shlibs field.  See the packaging manual.
> SERIOUS WARNING: /sw/build.build/root-alpine-2.22-1.5/sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib appea
> rs to have been linked using a flat namespace.
>        If this package BuildDepends on libtool2, make sure that you use
>           BuildDepends: libtool2 (>= 2.4.2-4).
>        and use autoreconf to regenerate the configure script.
>        If the package doesn't BuildDepend on libtool2, you'll need to
>        update its build procedure to avoid passing
>           -Wl,-flat_namespace
>        when linking libraries.
>
> 		  If this package actually requires a flat namespace build,
> 		  then ignore this message.
> 
> Removing runtime build-lock...
> 
> The following ConfigureParams fix all the above but lose everything related to web alpine, which we've never had anyway:
> 
> ConfigureParams: <<
> 	--disable-debug \
> 	--with-ssl-dir=%p \
> 	--with-ssl-certs-dir=%p/etc/ssl/certs \
> 	--with-ldap-dir=%p \
> 	--with-local-password-cache-method \
> 	--without-pubcookie \
> 	--without-tcl
> <<
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE43U3MLHUUDJBF5B53DRQHZ5LA5CNFSM4MQ2FYDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEU774GY.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by htodd** [comment]
Ugh, nm. Looks like the changes are in my stash.

On Wed, 6 May 2020, nieder wrote:

> 
> After commit c5526b4, I get these validation errors:
> 
> Validating .deb dir /sw/build.build/root-alpine-2.22-1.5...
> Error: File installed outside of allowable subdirectories of /sw
> 	Offending file: /sw/build.build/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpined
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/bin/alpineldap
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.a
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.dylib
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/alpine
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pico
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/pilot
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpdump
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/bin/rpload
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/alpine.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pico.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/pilot.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpdump.1
> 	Offending file: /sw/build.build/root-alpine-2.22-1.5/sw/share/man/man1/rpload.1
> Error: Published libtool compiler information points to fink build dir.
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> Error: The -framework flag may get munged by libtool. See the gcc manpage for information about passing multi-word options to fl
> ags for specific compiler passes.
> 	Offending file: /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.la
> 	Offending line: inherited_linker_flags='  -framework Carbon -framework ApplicationServices -framework Security'
> Error: package contains the shared library
>           /sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib
>        but the corresponding install_name and compatibility_version
>           %p/build.build/alpine-2.22-1.5/alpine-2.22/web/src/alpined.d/../../lib/libwpcomm.1.dylib 2.0.0
>        are not listed in the Shlibs field.  See the packaging manual.
> SERIOUS WARNING: /sw/build.build/root-alpine-2.22-1.5/sw/build.build/alpine-2.22-1.5/alpine-2.22/web/lib/libwpcomm.1.dylib appea
> rs to have been linked using a flat namespace.
>        If this package BuildDepends on libtool2, make sure that you use
>           BuildDepends: libtool2 (>= 2.4.2-4).
>        and use autoreconf to regenerate the configure script.
>        If the package doesn't BuildDepend on libtool2, you'll need to
>        update its build procedure to avoid passing
>           -Wl,-flat_namespace
>        when linking libraries.
>
> 		  If this package actually requires a flat namespace build,
> 		  then ignore this message.
> 
> Removing runtime build-lock...
> 
> The following ConfigureParams fix all the above but lose everything related to web alpine, which we've never had anyway:
> 
> ConfigureParams: <<
> 	--disable-debug \
> 	--with-ssl-dir=%p \
> 	--with-ssl-certs-dir=%p/etc/ssl/certs \
> 	--with-ldap-dir=%p \
> 	--with-local-password-cache-method \
> 	--without-pubcookie \
> 	--without-tcl
> <<
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE43U3MLHUUDJBF5B53DRQHZ5LA5CNFSM4MQ2FYDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEU774GY.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by htodd** [comment]
OK, updates pushed (I hope).

**Pull request merged**
