### PR TITLE
Atlas 3.10.3

### PR DESCRIPTION
**Pull request by nieder**
Update atlas to latest stable 3.10.3.
Also bumps internal LAPACK. There are newer LAPACK releases, but 3.6.1 was the latest available when 3.10.3 was released, so most likely to not introduce any issues.

### CODE REVIEW

**Comment by dhomeier** [comment]
Built without errors on 10.12; also rebuilt qrupdate-atlas, arpack-ng-atlas and octave382-atlas successfully with the updated version.

I found two issues with the atlas-doc splitoff, though:
1. Validation fails on my case-sensitive FS due to a conflict between `/sw/share/man/man3/c_intface.3`
`/sw/share/man/man3/C_INTFACE.3`
Both are simply pointers to `Cintface.c.3`, so there's probably no harm in removing one of them or ignoring it.

2. `atlas-doc` installs 2 (3?) afaict identical copies of the complete `LAPACK/html` docs with 1.2 GB of files each. The current version has 3 copies of 1 GB each under `/sw/share/doc/atlas{,-doc,-shlibs}`. Seems a bit excessive...

**Comment by nieder** [comment]
1) I get this on a case insensitive system:
```
$ dpkg-deb -c atlas-doc_3.10.2-5_darwin-x86_64.deb | grep -i c_intface
[nothing]
$ dpkg-deb -c atlas-doc_3.10.3-1_darwin-x86_64.deb | grep -i c_intface
-rw-r--r-- root/admin       22 2020-01-16 11:28 ./sw/share/man/man3/c_intface.3
-rw-r--r-- root/admin       22 2020-01-16 11:28 ./sw/share/man/man3/c_intface_.3
-rw-r--r-- root/admin       22 2020-01-16 11:28 ./sw/share/man/man3/c_intface__.3
```
I'm rebuilding to see where the capitalized file is made and see where I would need to delete it if needed.

2) I only see symlinks to the docs, not replication:
```
$ ls -ld /sw/share/doc/atlas*
drwxr-xr-x  23 root  admin  782 Jan 21 19:46 /sw/share/doc/atlas/
lrwxr-xr-x   1 root  admin    5 Jan 21 19:44 /sw/share/doc/atlas-doc@ -> atlas
lrwxr-xr-x   1 root  admin    5 Jan 21 19:46 /sw/share/doc/atlas-shlibs@ -> atlas
$ du -sh atlas*
1.2G	atlas
4.0K	atlas-doc
4.0K	atlas-shlibs
```
And the deb sizes agree:
```
-rw-r--r--  1 root  wheel   154M Jan 16 11:43 atlas-doc_3.10.3-1_darwin-x86_64.deb
-rw-r--r--  1 root  wheel   9.6M Jan 16 11:41 atlas-shlibs_3.10.3-1_darwin-x86_64.deb
-rw-r--r--  1 root  wheel   7.1M Jan 16 11:41 atlas_3.10.3-1_darwin-x86_64.deb
```

**Comment by dhomeier** [comment]
I have the underscored versions as well, but only in lower case.

> ```
> $ du -sh atlas*
> 1.2G	atlas
> 4.0K	atlas-doc
> 4.0K	atlas-shlibs
> ```
Sorry, I had added the trailing slashes to the paths, making `du` follow the links! Removing `atlas-doc` frees about 1 GB, so that's consistent.

**Comment by nieder** [comment]
The man files are just created into LAPACK/DOCS at the end of CompileScript and then manually copied into %i/share/man. We can directly remove C_INTFACE.3, but I have no way of testing to make sure it was done properly. Prob `rm -f %i/share/man/man3/C_INTFACE.3`. Are there other manfiles in man3 that are problematic in case sensitive installs?

**Comment by dhomeier** [comment]
`find . -iname ...` only located this pair.

The InstallScript already removes a few of the manpages; I could test this perhaps with something like
```
[ -f %i/share/man/man3/C_INTFACE.3 ] && [ ! %i/share/man/man3/C_INTFACE.3 -ef %i/share/man/man3/c_intface.3 ] && rm %i/share/man/man3/C_INTFACE.3
```

**Comment by nieder** [comment]
Sounds like a reasonable check. Did it pass validation after that?

**Comment by dhomeier** [comment]
It did; `man C_INTFACE` now produces no results on my system (don't know if it would on case-insensitive FS).

I noticed some errors in the test runs because the patch script was setting a broken path
`LAPACKLIB    = lib/scratch.noindex/fink.build/atlas-3.10.3-1/ATLAS/../bld/lib/liblapack.a`
in LAPACK/make.inc.proto, but the absolute path would not work anyway, since the Makefiles are all calling that macro as `../$(LAPACKLIB)`. Same for `TMGLIB`. I got most things to work with this patch
```
@@ -117,9 +117,9 @@
 cd ..
 cd LAPACK
 sed -e 's,\.\./.\./librefblas\.a,%b/../bld/lib/libf77blas.a %b/../bld/lib/libcblas.a %b/../bld/lib/libatlas.a,' \
-    -e 's,lapack\.a,%b/../bld/lib/liblapack.a,' \
-    -e 's, -g$,,' -e '/LOADOPTS/s,=,= $(OPTS),' \
-    -e 's,libtmglib.a,%b/../bld/src/lapack/reference/libtmglib.a,' < make.inc.example > make.inc.proto
+    -e 's,liblapack\.a,../darwin_bld/lib/liblapack.a,' \
+    -e 's,libtmglib.a,../darwin_bld/src/lapack/reference/libtmglib.a,' \
+    -e 's, -g$,,' -e '/LOADOPTS/s,=,= $(OPTS),' < make.inc.example > make.inc.proto
 path=`which perl`
 sed -i'' -e "s,/s./bin/perl,$path," DOCS/Doxyfile*
 <<
@@ -246,6 +246,10 @@
  find %i/lib -type f -name '*.a' -exec ranlib \{\} \;
  chmod -R a-x %i/lib/*
  chmod -R a+rX %i/share
+
+ # rm manpage causing a conflict on case-insensitive FS (actually just a reference to Cintface.c.3)
+ cd %i/share/man/man3
+ [ -f C_INTFACE.3 ] && [ ! C_INTFACE.3 -ef c_intface.3 ] && rm C_INTFACE.3
 <<
 Splitoff: <<
 	Package: %N-shlibs
```
a couple errors still remaining of the kind
```
/sw/bin/gfortran-fsf-9 -fPIC -fomit-frame-pointer -O3 -m64 -mfpmath=sse -m64 -fPIC  aladhd.o alaerh.o alaesm.o alahd.o alareq.o alasum.o alasvm.o chkxer.o icopy.o ilaenv.o xlaenv.o xerbla.o dlaord.o  zchkaa.o zchkeq.o zchkgb.o zchkge.o zchkgt.o zchkhe.o zchkhp.o zchklq.o zchkpb.o zchkpo.o zchkps.o zchkpp.o zchkpt.o zchkq3.o zchkql.o zchkqp.o zchkqr.o zchkrq.o zchksp.o zchksy.o zchktb.o zchktp.o zchktr.o zchktz.o zdrvgt.o zdrvhp.o zdrvls.o zdrvpb.o zdrvpp.o zdrvpt.o zdrvsp.o zerrgt.o zerrlq.o zerrls.o zerrps.o zerrql.o zerrqp.o zerrqr.o zerrrq.o zerrtr.o zerrtz.o zgbt01.o zgbt02.o zgbt05.o zgelqs.o zgeqls.o zgeqrs.o zgerqs.o zget01.o zget02.o zget03.o zget04.o zget07.o zgtt01.o zgtt02.o zgtt05.o zhet01.o zhpt01.o zlaipd.o zlaptm.o zlarhs.o zlatb4.o zlatb5.o zlatsp.o zlatsy.o zlattb.o zlattp.o zlattr.o zlavhe.o zlavhp.o zlavsp.o zlavsy.o zlqt01.o zlqt02.o zlqt03.o zpbt01.o zpbt02.o zpbt05.o zpot01.o zpot02.o zpot03.o zpot05.o zpst01.o zppt01.o zppt02.o zppt03.o zppt05.o zptt01.o zptt02.o zptt05.o zqlt01.o zqlt02.o zqlt03.o zqpt01.o zqrt01.o zqrt01p.o zqrt02.o zqrt03.o zqrt11.o zqrt12.o zqrt13.o zqrt14.o zqrt15.o zqrt16.o zqrt17.o zrqt01.o zrqt02.o zrqt03.o zrzt01.o zrzt02.o zsbmv.o  zspt01.o zspt02.o zspt03.o zsyt01.o zsyt02.o zsyt03.o ztbt02.o ztbt03.o ztbt05.o ztbt06.o ztpt01.o ztpt02.o ztpt03.o ztpt05.o ztpt06.o ztrt01.o ztrt02.o ztrt03.o ztrt05.o ztrt06.o ztzt01.o ztzt02.o dget06.o zgennd.o zerrvx.o zdrvge.o zdrvsy.o zdrvgb.o zerrge.o zdrvpo.o zdrvhe.o zerrpo.o zerrsy.o zerrhe.o \
        /scratch.noindex/fink.build/atlas-3.10.3-1/darwin_bld/lib/lapack_matgen.a /scratch.noindex/fink.build/atlas-3.10.3-1/darwin_bld/lib/liblapack.a   /scratch.noindex/fink.build/atlas-3.10.3-1/darwin_bld/lib/libf77blas.a /scratch.noindex/fink.build/atlas-3.10.3-1/darwin_bld/lib/libcblas.a /scratch.noindex/fink.build/atlas-3.10.3-1/darwin_bld/lib/libatlas.a -lpthread -lm -o xlintstz
Undefined symbols for architecture x86_64:
  "_zgelsx_", referenced from:
      _zdrvls_ in zdrvls.o
      _zerrls_ in zerrls.o
```
– these symbols are later merged into `liblapack.a` and `lib[st]atlas.dylib`, but apparently not in the test builds...

**Pull request merged**
