### PR TITLE
Add r-base36

### PR DESCRIPTION
**Pull request by babayoshihiko**
R 3.6.1 has been added.  CRAN and Bioconductor packages will follow.

### CODE REVIEW

**Comment by nieder** [comment]
Should probably bump readline6 to readline7 unless it's known to fail.

Can we also bump the gcc5 BuildDepends to gcc8? That would probably need to be propagated across all the rmods that use gfortran to build, however.

**Comment by babayoshihiko** [comment]
> Should probably bump readline6 to readline7 unless it's known to fail.
> 
> Can we also bump the gcc5 BuildDepends to gcc8? That would probably need to be propagated across all the rmods that use gfortran to build, however.

Can we stay with readline6 and gcc5 for R <=3.5?

For CRAN, we may use:
(%type_raw[rversion] < 3.6) gcc5-shlibs | (%type_raw[rversion] >= 3.6) gcc8-shlibs,
and so on.

**Comment by nieder** [comment]
@babayoshihiko yes to keeping R <= 3.5 at the older readline/gcc.

**Comment by nieder** [comment]
I recommend switching r-base36 to gcc9 (not gcc8 as I said earlier).  I just patched gcc9 to build on 10.15, and currently, it's the only gccX that builds on 10.15.

**Comment by babayoshihiko** [comment]
> I recommend switching r-base36 to gcc9 (not gcc8 as I said earlier). I just patched gcc9 to build on 10.15, and currently, it's the only gccX that builds on 10.15.

Now r-base depends on gcc9 (and readline7).

I am building CRAN and bioconductor packages.  So far, there seems no problem.

**Pull request merged**
