### PR TITLE
Nut update

### PR DESCRIPTION
**Pull request by dmacks**
openssl upgrade (for issue #499), and general dependency and build-system audit/fixes

### CODE REVIEW

**Comment by clepple** [comment]
@dmacks thanks for putting this together. The build logs look good, and I plan to do some runtime testing this afternoon.

The `CFLAGS` -> `CPPFLAGS` changes generally made sense for the `-I` flags, but if that's the case in general, we might want to rename all of them upstream. The only catch would be if some of the pkgconfig files are introducing other flags. Haven't had a chance to check on that myself, but if you already researched that, I'll take your word for it.

**Comment by nieder** [comment]
@dmacks ping

**Comment by dmacks** [comment]
@nieder does this also resolve #636?

**Comment by nieder** [comment]
@dmacks probably. Untested, but this explicitly BDepends on libnetsnmp35, so that should deal with the failure I saw on 10.14.5.

**Comment by nieder** [comment]
ping?

**Comment by clepple** [comment]
Sorry for the massive delay - I was hoping we'd have another release out by this point, but that's just not in the cards. Still don't have a great setup for testing here.

**Review by clepple — APPROVED** [review]
LGTM

**Pull request merged**
