### PR TITLE
Turn off R31 on 10.13

### PR DESCRIPTION
**Pull request by dmacks**
Per #17, add -r33 as necessary and Distribution tag to stop carrying -r31 along beyond 10.12 (same as -r32 already is)

### CODE REVIEW

**Comment by dmacks** [comment]
Pending coordination with #16 (will make one of its commits moot) to avoid diverging forks...

**Comment by nieder** [comment]
I've got a bunch of people in my house limiting access to my production machine. Will clear up by Sunday night.

**Comment by dmacks** [comment]
I should have re based rather than merged, so there is no cruft. And now there's still a xconflict even after merging that? I'll fiddle with it in a day or two, or can just cherry pick the relevant commits instead of merging.

**Comment by dmacks** [comment]
All the key parts are cherry-picked or hand-redone to avoid conflicts.

**Pull request closed without merging**
