### PR TITLE
Graphviz update

### PR DESCRIPTION
**Pull request by dmacks**
New version, and fixes runtime crash due to some sort of libxt chaos.

### CODE REVIEW

**Comment by nieder** [comment]
Does this need to use old libnetsnmp30? We have libnetsnmp35 (which doesn't build on 10.15+) so I'm working on libnetsnmp40 (v5.9)

**Comment by dmacks** [comment]
d80436d avoids libnetsnmp altogether.

**Comment by nieder** [comment]
```
Validating .deb dir /opt/sw/build.build/root-libgraphviz238-shlibs-2.46.0-2...
Warning: Shlibs field specifies private install_name '/opt/sw/lib/graphviz-2.38/graphviz/tcl/libgdtclft.0.dylib', but it does not exist!
Warning: Shlibs field specifies private install_name '/opt/sw/lib/graphviz-2.38/graphviz/tcl/libtcldot.0.dylib', but it does not exist!
Warning: Shlibs field specifies private install_name '/opt/sw/lib/graphviz-2.38/graphviz/tcl/libtcldot_builtin.0.dylib', but it does not exist!
Warning: Shlibs field specifies private install_name '/opt/sw/lib/graphviz-2.38/graphviz/tcl/libtclplan.0.dylib', but it does not exist!
Package looks good!
```

**Comment by dmacks** [comment]
What does your ./configure output say about tcl? On my 10.13:
```
checking tcl.h usability... yes
checking tcl.h presence... yes
checking for tcl.h... yes
using /System/Library/Frameworks/Tcl.framework/tclConfig.sh
[...]
  gv_tcl:        Yes

  tcldot:        Yes
  tclpathplan:   Yes
  gdtclft:       Yes
```

**Comment by nieder** [comment]
```
checking tcl.h usability... yes
checking tcl.h presence... yes
checking for tcl.h... yes
configure: WARNING: Unable to find tclConfig.sh. The Tcl packages will not be built
...
  gv_tcl:        No (tcl not available)

  tcldot:        No (tcl not available)
  tclpathplan:   No (tcl not available)
  gdtclft:       No (tcl not available)
```

This is what config.log says:
```
configure:23714: checking tcl.h usability
configure:23714: gcc -c -g -O2 -Wall -Wextra -Wmissing-include-dirs -Wswitch-default -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wconversion -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -fno-common -Wall   conftest.c >&5
configure:23714: $? = 0
configure:23714: result: yes
configure:23714: checking tcl.h presence
configure:23714: gcc -E   conftest.c
configure:23714: $? = 0
configure:23714: result: yes
configure:23714: checking for tcl.h
configure:23714: result: yes
configure:23750: WARNING: Unable to find tclConfig.sh. The Tcl packages will not be built
```

I don't have any Fink tcltk package installed, and system-tclConfig.sh only lives in the SDKs (not directly in /System/Library/Frameworks/Tcl.framework)

**Comment by dmacks** [comment]
The intent is to use system-tcltk, which is apparently a moving target. The package has long had a PatchScript about it:
```
        # No /usr/lib/tclConfig.sh on 10.13; this is portable
        # to all 10.x:
        perl -pi -e 's|\$\{TCLSH_EXEC_PREFIX\}/lib/tclConfig.sh|/System/Library/Frameworks/Tcl.framework/tclConfig.sh|g' configure
```
Any idea if there is a unified incantation that will work for everyone now?

**Comment by nieder** [comment]
use `xcrun --sdk macosx --show-sdk-path` to grab the SDK path on 10.14 and up, then perl pie to this instead: `${SDK_PATH}/System/Library/Frameworks/Tcl.fr...`. $SDK_PATH will be empty below 10.14, so identical to current, and 10.14+ will get the correct location.
The pythonXX.info files have a sample.

**Comment by dmacks** [comment]
(rebased on master to fix merge conflict)

**Comment by dmacks** [comment]
Hold on, that's not right. Will fix it later today

**Review by nieder — APPROVED** [review]
LGTM on 10.15

**Pull request merged**
