### PR TITLE
Perl5282

### PR DESCRIPTION
**Pull request by nieder**
This creates the new package perl5282, to match system perl on macOS 11.0. It's basically a copy of perl5184, with some necessary test fixes grabbed from upstream.

### CODE REVIEW

**Comment by nieder** [comment]
One thing that might need editing is the list of provided packages. How was that original list generated? Is there a perl command to output the available mods?

**Comment by dmacks** [comment]
'corelist' (via module-corelist-pmXXX) can help. I keep Fink::VirtPackage's system-perlXXX provides: lists up-to-date. We generally haven't bothered adding to these lists, only removing (among other reasons, they are so incomplete and always have been).

**Comment by nieder** [comment]
Yeah, so `corelist -v 5.14.4` says there are 689 modules provided by CORE. So not going to update.

**Comment by nieder** [comment]
Ping on committing?

**Comment by nieder** [comment]
Will push soon to start populating pm5282 mods

**Pull request merged**
