### PR TITLE
Update astroid info for python versions 3.9 and 3.10

### PR DESCRIPTION
**Pull request by sth0**
Simple addition of 3.9 and 3.10 to python versions for astroid.  I have a package that I haven't pushed an update for years but have a bunch of these updates in my local tree.

### CODE REVIEW

**Comment by nieder** [comment]
Needs #1140

**Comment by nieder** [comment]
Also need to update lazy-object-proxy-py to have py310 variant
```
WARNING: While resolving dependency "lazy-object-proxy-py310" for package "astroid-py310-2.2.5-3", package "lazy-object-proxy-py310" was not found.
Can't resolve dependency "lazy-object-proxy-py310" for package "astroid-py310-2.2.5-3" (no matching packages/versions found)
Exiting with failure.
```

The lazy-object-proxy-py package might benefit from the newer releases than what we have (although 1.10.0 needs newer setuptools than what we can currently have).

**Comment by sth0** [comment]
see PR #1144, for update to lazy-object-proxy.
(I have a lot of these simple updates!)

**Review by nieder — APPROVED** [review]
lgtm

**Pull request merged**
