### PR TITLE
Fluidsynth

### PR DESCRIPTION
**Pull request by docoder-prog**

### CODE REVIEW

**Comment by docoder-prog** [comment]
Can you be more specific: what is the correct sub directory?

**Comment by nieder** [comment]
The files go into `fink-distributions/10.9-libcxx/stable/main/finkinfo/sound`, but the files you added are at the root of your fork. I don't know why they're not showing up when you use `find`, but you can see them in the webview:

https://github.com/docoder-prog/fink-distributions/tree/fluidsynth

**Comment by docoder-prog** [comment]
> On May 23, 2020, at 8:37 AM, nieder <notifications@github.com> wrote:
> 
> 
> The files go into fink-distributions/10.9-libcxx/stable/main/finkinfo/sound, but the files you added are at the root of your fork. I don't know why they're not showing up when you use find, but you can see them in the webview:
> 
> https://github.com/docoder-prog/fink-distributions/tree/fluidsynth <https://github.com/docoder-prog/fink-distributions/tree/fluidsynth>
I did the below early yesterday morning and it was reported in my previous pull request.

% git push --set-upstream origin fluidsynth  //branch pushed to remote copy of clone
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'fluidsynth' on GitHub by visiting:
remote:      https://github.com/docoder-prog/fink-distributions/pull/new/fluidsynth <https://github.com/docoder-prog/fink-distributions/pull/new/fluidsynth>
remote: 
To https://github.com/docoder-prog/fink-distributions <https://github.com/docoder-prog/fink-distributions>
 * [new branch]            fluidsynth -> fluidsynth
Branch 'fluidsynth' set up to track remote branch 'fluidsynth' from 'origin’.

 % git commit
On branch fluidsynth
Your branch is up to date with 'origin/fluidsynth'.

Changes not staged for commit:
	modified:   10.9-libcxx/stable/main/finkinfo/sound/fluidsynth1.info <http://fluidsynth1.info/>
	deleted:    fluidsynth1.info <http://fluidsynth1.info/>
	deleted:    fluidsynth2.info <http://fluidsynth2.info/>

Untracked files:
	10.9-libcxx/stable/main/finkinfo/sound/fluidsynth2.info <http://fluidsynth2.info/>

no changes added to commit

I have just done the following (green) now:

fink-distributions % git push
Everything up-to-date

fink-distributions % git pull
Already up to date.

fink-distributions % ls
10.2			10.4-transitional	VERSION
10.2-gcc3.3		10.7			compare-trees.pl
10.3			10.9-libcxx		inject.pl
10.4			README			stamp-cvs-live

I suggest we wait and see if the change reflects on your side in the next two days. If not, I’ll close this request and do another one Tuesday.

**Comment by dmacks** [comment]
In the fluidsynth1.info, looking at the Shlibs line:
```
-Shlibs: %p/lib/%N/lib/libfluidsynth.1.dylib 1.0.0 %n (>= 1.1.2-358)
+Shlibs: %p/lib/%N/lib/libfluidsynth.1.dylib 1.0.0 %n (>= 1.1.11-1)
```
Because the compatibility_version (1.0.0) is not changing, the package-version dependency (>= 1.1.2-358) should not change either. It is defined as "the minimum pkgversion that supplies that given c_v", not simply a dup of the %v-%r of the .info file.

**Comment by docoder-prog** [comment]
I managed to delete the info files using the GitHub GUI since ‘git rm’ did from Terminal does not reflect on
https://github.com/docoder-prog/fink-distributions/tree/fluidsynth <https://github.com/docoder-prog/fink-distributions/tree/fluidsynth>. Then I did the following:

% git push
To https://github.com/docoder-prog/fink-distributions
 ! [rejected]              fluidsynth -> fluidsynth (fetch first)
error: failed to push some refs to 'https://github.com/docoder-prog/fink-distributions'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

fink-distributions % git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/docoder-prog/fink-distributions
   5b4b633f1c..a8d9f4a855  fluidsynth -> origin/fluidsynth
   5b4b633f1c..6196c84e27  master     -> origin/master
Updating 5b4b633f1c..a8d9f4a855
Fast-forward
 fluidsynth1.info | 103 ----------------------------------------------------
 fluidsynth2.info | 107 -------------------------------------------------------
 2 files changed, 210 deletions(-)
 delete mode 100644 fluidsynth1.info
 delete mode 100644 fluidsynth2.info <http://fluidsynth2.info/>

% git push
Everything up-to-date

When I looked at https://github.com/docoder-prog/fink-distributions/tree/fluidsynth <https://github.com/docoder-prog/fink-distributions/tree/fluidsynth>
the info files in the top-level are now gone. So, working within the GitHub URL GUI now reflects (obviously) on the webview.

I have to check now to see if the new info files in 10.9-libcxx/stable/main/finkinfo/sound/ exist on
https://github.com/docoder-prog/fink-distributions/tree/fluidsynth <https://github.com/docoder-prog/fink-distributions/tree/fluidsynth>. No … so I edited the fluidsynth1.info <http://fluidsynth1.info/> file manually on the fluidsynth branch URL. 

While trying to upload fluidsynth2.info <http://fluidsynth2.info/> again using the GitHub URL GUI, a new branch was automagically created: “patch-1”.

So I will try uploading fluidsynth2.info <http://fluidsynth2.info/> via the patch-1 branch later. For now, let’s wait to see how the fluidsynth1 update pans out… 

(It is quite evident that uploading files from Terminal using a long path name does not seem to reflect on the GitHub URL. Whatever the reason(s) for this; I am forced to use the web view GUI.)

Keep me posted. Regards, E

**Comment by docoder-prog** [comment]
The fluidsynth1.info file has been added to the "docoder-prog:patch-1"  branch. "patch-1" also contains the new fluidsynth2.info file.

**Pull request closed without merging**
