### PR TITLE
fluidsynth3.info

### PR DESCRIPTION
**Pull request by docoder-prog**
Please find enclosed the fluidsynth3.info file for merging into fink/fink-distributions. 
[fluidsynth3.zip](https://github.com/fink/fink-distributions/files/11471374/fluidsynth3.zip)

### CODE REVIEW

**Review by nieder — CHANGES_REQUESTED** [review]
All I see here are merge commits and some deletes of misplaced files from the very old fluidsynth update. But there is no new `sound/fluidsynth3.info` file.

**Comment by docoder-prog** [comment]
> All I see here are merge commits and some deletes of misplaced files from the very old fluidsynth update. But there is no new `sound/fluidsynth3.info` file.

fluidsynth3.info added to 10.9-libcxx/stable/main/finkinfo/sound/ as per request.

**Comment by docoder-prog** [comment]
fluidsynth3.info added to 10.9-libcxx/stable/main/finkinfo/sound/ as per request.

**Review by nieder — CHANGES_REQUESTED** [review]
Thanks for the update. Just a couple things:
1) ladspa is listed in the depends, but not detected. Adding `-I%p/include` to CMAKE_C_FLAGS finds it.
2) Add fluidsynth3-dev to the fink-package-precedence command. Can also remove fluidsynth-dev since that's never existed in the 10.9 tree.
3) the symlink for `fluidsynth.pc` points to the unversioned `%p/lib/fluidsynth` directory, but we're installing in `%p/lib/%N` which is versioned.

**Comment by docoder-prog** [comment]
Changes made and uploaded. E

**Comment by nieder** [comment]
Committed this directly in 7a6384b9fb69098b813cfffa452400fef6c632b8
Thanks for the update!

For future updates, I recommend following the directions [here](https://github.com/fink/fink-distributions/wiki/Submitting-new-or-updated-packages) for using branches to help keep the commit history clean.

**Comment by docoder-prog** [comment]
> Committed this directly in [7a6384b](https://github.com/fink/fink-distributions/commit/7a6384b9fb69098b813cfffa452400fef6c632b8) Thanks for the update!
> 
> For future updates, I recommend following the directions [here](https://github.com/fink/fink-distributions/wiki/Submitting-new-or-updated-packages) for using branches to help keep the commit history clean.

Noted.
Greetings.

**Pull request closed without merging**
