### PR TITLE
Lazarus: Update to new upstrem version (1.8.2)

### PR DESCRIPTION
**Pull request by kamischi**
Lazarus: Update to new upstrem version (1.8.2).
Lazarus based on Qt5 is new.

### CODE REVIEW

**Comment by nieder** [comment]
I get this error on 10.11:
````
(9001) Assembling (pipe) ../units/x86_64-darwin/qt5/lazarus.s
(9022) Compiling resource ../units/x86_64-darwin/qt5/lazarus.or
(9015) Linking ../lazarus
ld: framework not found Qt5Pas
An error occurred while linking 
lazarus.pp(163) Error: (9013) Error while linking
lazarus.pp(163) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
make[2]: *** [Makefile:3961: lazarus] Error 1
make[2]: Leaving directory '/sw/build.build/lazarus-qt5-1.8.2-1/lazarus/ide'
````

**Comment by nieder** [comment]
That's when building lazarus-qt5-1.8.2-1

**Comment by kamischi** [comment]
Oops. That is an issue, i have forgotten during a pause, when working on the descriptions. Thanks for pointing it out. The fix should be easy, but the tests take their time, mainly because compiling c++ code is so much slower than the pascal code. Expect a new version of lazarus.info AND lazarus-lcl-qt5.info and a new qt5pas.info within a couple of days.

**Comment by nieder** [comment]
Sounds good. You can then just commit those changes to the same branch in your fork, git push, and it will automatically be updated in this PR.

**Comment by kamischi** [comment]
Lazarus.info and lazarus-lcl-qt5.info are updated. qt5pas.info has been added. This should fix the issue and result in a cleaner structure of dependencies and way to build stuff.

**Pull request merged**
