### PR TITLE
lighttpd: update to lighttpd 1.4.74

### PR DESCRIPTION
**Pull request by gstrauss**
lighttpd: update to lighttpd 1.4.74

### CODE REVIEW

**Comment by gstrauss** [comment]
(might need minor patch to find ../compat/sys/queue.h)

**Comment by dmacks** [comment]
With the patch, builds fine on my 10.13 (once I updated the Patch-MD5 for the new .patch). I see it's using lua51, which is pretty old. The configure script seems to accept up to lua54, and it builds equivalently for me if I update the deps for that.

**Comment by gstrauss** [comment]
Thanks.  I updated the MD5 for lighttpd.patch and pushed the change to this PR.

FYI: lighttpd mod_magnet supports lua 5.1 and later, including 5.2, 5.3, and 5.4.  Also supported is lua-jit, which is based on lua 5.1.

fink maintainers may safely choose to modify lighttpd.info to use lua54.

**Comment by gstrauss** [comment]
Replaced by #1130 for lighttpd 1.4.75

**Pull request closed without merging**
