### PR TITLE
postgresql updates Nov  2018

### PR DESCRIPTION
**Pull request by wodev**
postgresql updates November 2018:

- Update PG 10  to 10.6
- Update PG 9.6  to 9.6.11
- Update PG 9.5  to 9.5.15
- Update PG 9.4  to 9.4.20

Upstream fixed build issues on 10.14 for all supported versions ( Issue #291 ).
Contains preparation for new major version postgresql 11.

### CODE REVIEW

**Comment by nieder** [comment]
On 10.11 with xcode8, pg10 fails in the final link step for postgres:
````
checking for library containing clock_gettime... none required
...
checking for clock_gettime... yes
...
<lots of .o files> ../../src/common/libpgcommon_srv.a -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lm -o postgres
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _ExplainOneQuery in explain.o
      _ExplainOnePlan in explain.o
      _ExplainExecuteQuery in prepare.o
      _lazy_vacuum_rel in vacuumlazy.o
      _InstrStartNode in instrument.o
      _InstrStopNode in instrument.o
      _pgstat_init_function_usage in pgstat.o
      ...
ld: symbol(s) not found for architecture x86_64
````
Online searching indicates that clock_gettime didn't get added until 10.12, but I don't know why ./configure is reporting it as found on 10.11.

postgresql9* built fine.

**Comment by wodev** [comment]
Xcode 8 only contains  SDK12, that's why configure finds clock_gettime .
With commit 0a6bc28 I added a fix for 10.11 with xcode8.

**Comment by nieder** [comment]
Xcode8 fix worked. But I get a failure during TestScript. tmp_install/log/install.log that's generated says:
````
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /sw/build.build/postgresql10-10.6-1/postgresql-10.6/tmp_install/sw/opt/postgresql-10/bin/vacuumdb (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
````
Adding `-headerpad_max_install_names` to LDFLAGS makes everything finish correctly.

**Comment by wodev** [comment]
I added the LDFLAG  with the latest commit  e1ac07b .

**Pull request merged**
