### PR TITLE
Build maxima v5.41.0 matching sbcl 1.4.16

### PR DESCRIPTION
**Pull request by leighsmith**
- Updated maxima v5.41.0 to work with sbcl v1.4.16.
- Incorporates patches to build aquaterm as specified in https://github.com/fink/fink-distributions/pull/334

### CODE REVIEW

**Comment by akhansen** [comment]
Oops, missed seeing this earlier.  I had packaging for 5.42.2 made up, so I went with that.

**Comment by akhansen** [comment]
Oh, by the way, would you still be interested in taking aquaterm on?

**Comment by leighsmith** [comment]
Yes I can take on aquaterm. Do you want me to submit a separate pull request for that?

**Comment by akhansen** [comment]
I just changed that manually.  Thanks!

**Pull request closed without merging**
