### PR TITLE
More CRAN packages for R 4.1 and 4.0

### PR DESCRIPTION
**Pull request by babayoshihiko**
More CRAN packages.

Three packages has a license [CeCILL-2](http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt). Is this OSI-Approved?
https://cran.r-project.org/web/packages/optimbase/index.html

### CODE REVIEW

**Comment by dmacks** [comment]
OSI rejected CeCILL-2, but accepted CeCILL-2.1. The package authors would have to upgrade their packages to 2.1.

**Comment by babayoshihiko** [comment]
> OSI rejected CeCILL-2, but accepted CeCILL-2.1. The package authors would have to upgrade their packages to 2.1.

The packages were GPL-licensed in the previous versions.

Can we set License: Resitrictive? Or Is it better to keep the previous version?

The pacakges are:

cran-neldermead-r.info
cran-optimbase-r.info
cran-optimsimplex-r.info

**Comment by dmacks** [comment]
> Can we set License: Resitrictive? Or Is it better to keep the previous version?

I'm ambivalent. Does Debian or other distro have them? Following the lead of a strongly "free and open software" community usually feels safe.

**Comment by babayoshihiko** [comment]
> > Can we set License: Resitrictive? Or Is it better to keep the previous version?
> 
> I'm ambivalent. Does Debian or other distro have them? Following the lead of a strongly "free and open software" community usually feels safe.

The three packages have been reverted.

For the time being, I would like to focus on other CRAN packages.

**Review by dmacks — APPROVED** [review]
LGTM by eye, I didn't test-build them all. Thanks for the checksum upgrades!

**Pull request merged**
