### PR TITLE
libdbi upgrade

### PR DESCRIPTION
**Pull request by dmacks**

### CODE REVIEW

**Comment by dmacks** [comment]
This is all Dave Reiser's. Anyone know if he's on github?

**Comment by nieder** [comment]
Do the tests for the new (or old) libdbi-drivers-pgsql94 work?  They hang here for me with the old version.

**Comment by dmacks** [comment]
They had never worked for me IIRC. Can't remember if they hang or required that the package be already installed, or required some other setup of system servers.

**Comment by nieder** [comment]
@dbreiser

**Comment by nieder** [comment]
These look OK to me and built on 10.13.
For the C/R issue, upstream has all of 2 commits since 2014, so I doubt it's going to get any love for newer pg versions? So just ignore resolving that aspect unless it becomes necessary?

**Comment by dmacks** [comment]
It's been a long time with no action and no objection.

**Pull request merged**
