### PR TITLE
libmaxminddb new package (version 1.3.2)

### PR DESCRIPTION
**Pull request by wodev**
new package for MaxMind DB Library libmaxminddb:
C library for the MaxMind DB file format http://maxmind.github.io/libmaxminddb/

 ilibmaxminddb	1.3.2-1	C library for the MaxMind DB file format
 libmaxminddb-dev	1.3.2-1	C library for the MaxMind DB file format
 ilibmaxminddb-shlibs	1.3.2-1	C library for the MaxMind DB file format

tested with fink -m rebuild libmaxminddb

Package Contents:
dpkg -c /sw/fink/dists/stable/main/binary-darwin-x86_64/libs/libmaxminddb-shlibs_1.3.2-1_darwin-x86_64.deb
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/lib/
-rwxr-xr-x  0 root   admin   25732  7 Apr 14:49 ./sw/lib/libmaxminddb.0.dylib
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/
-rw-r--r--  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/AUTHORS
-rw-r--r--  0 root   admin   12273  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/CHANGES.md
-rw-r--r--  0 root   admin   11358  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/LICENSE
-rw-r--r--  0 root   admin     558  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/NOTICE
-rw-r--r--  0 root   admin    4184  7 Apr 14:49 ./sw/share/doc/libmaxminddb-shlibs/README.md

dpkg -c /sw/fink/dists/stable/main/binary-darwin-x86_64/libs/libmaxminddb_1.3.2-1_darwin-x86_64.deb
drwxr-xr-x  0 root   admin       0  7 Apr 14:48 ./
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/bin/
-rwxr-xr-x  0 root   admin   19772  7 Apr 14:49 ./sw/bin/mmdblookup
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb/
-rw-r--r--  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb/AUTHORS
-rw-r--r--  0 root   admin   12273  7 Apr 14:49 ./sw/share/doc/libmaxminddb/CHANGES.md
-rw-r--r--  0 root   admin   11358  7 Apr 14:49 ./sw/share/doc/libmaxminddb/LICENSE
-rw-r--r--  0 root   admin     558  7 Apr 14:49 ./sw/share/doc/libmaxminddb/NOTICE
-rw-r--r--  0 root   admin    4184  7 Apr 14:49 ./sw/share/doc/libmaxminddb/README.md
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/man/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/man/man1/
-rw-r--r--  0 root   admin    2718  7 Apr 14:49 ./sw/share/man/man1/mmdblookup.1

dpkg -c /sw/fink/dists/stable/main/binary-darwin-x86_64/libs/libmaxminddb-dev_1.3.2-1_darwin-x86_64.deb
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/include/
-rw-r--r--  0 root   admin    7932  7 Apr 14:49 ./sw/include/maxminddb.h
-rw-r--r--  0 root   admin     507  7 Apr 14:49 ./sw/include/maxminddb_config.h
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/lib/
-rwxr-xr-x  0 root   admin     943  7 Apr 14:49 ./sw/lib/libmaxminddb.la
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/lib/pkgconfig/
-rw-r--r--  0 root   admin     269  7 Apr 14:49 ./sw/lib/pkgconfig/libmaxminddb.pc
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/
-rw-r--r--  0 root   admin       0  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/AUTHORS
-rw-r--r--  0 root   admin   12273  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/CHANGES.md
-rw-r--r--  0 root   admin   11358  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/LICENSE
-rw-r--r--  0 root   admin     558  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/NOTICE
-rw-r--r--  0 root   admin    4184  7 Apr 14:49 ./sw/share/doc/libmaxminddb-dev/README.md
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/man/
drwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/share/man/man3/
-rw-r--r--  0 root   admin   32960  7 Apr 14:49 ./sw/share/man/man3/libmaxminddb.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_aget_value.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_close.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_dump_entry_data_list.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_free_entry_data_list.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_get_entry_data_list.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_get_metadata_as_entry_data_list.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_get_value.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_lib_version.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_lookup_sockaddr.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_lookup_string.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_open.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_read_node.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_strerror.3
-rw-r--r--  0 root   admin      24  7 Apr 14:49 ./sw/share/man/man3/MMDB_vget_value.3
lrwxr-xr-x  0 root   admin       0  7 Apr 14:49 ./sw/lib/libmaxminddb.dylib -> libmaxminddb.0.dylib

### CODE REVIEW

**Comment by dmacks** [comment]
Passing -no-undefined when compiling shared libraries helps diagnose a class of possible runtime errors that are actually caused by library errors by triggering an error when the library itself is compiled. So something like:
```
perl -pi -e 's/-verison-info/-no-undefined -version-info/' src/Makefile.in
```
I don't get any such errors, but it's a useful trick in general.

There is a lot of compiling that happens in TestScript, so please put another fink-package-precedence call in it (you can just copy-paste the line from CompileScript).

During the self-test, I saw a warning:

```
PASS: compile_c++_t.pl
1..0 # skipp all tests skipped - this test requires the command line utility `nm`.
PASS: external_symbols_t.pl
```
In t/external_symbols_t.pl, the test for the presence of that utility is based on a linux-specific (or at least "not how darwin does it") invocation. The following patch converts it to how our nm acts:
```
perl -pi -e 's/-V/-version/' t/external_symbols_t.pl
```
But that leads to:
```
not ok 1 - No libs were found to test
#   Failed test 'No libs were found to test'
#   at ./external_symbols_t.pl line 53.
1..1
# Looks like you failed 1 test of 1.
FAIL: external_symbols_t.pl
```
so maybe that test really is not appropriate for darwin? Or else will require even more hacking to nm invocations or something to get it working. I can try to look sometime if you like.

**Comment by dmacks** [comment]
The nm-related test was failing because it was looking for the just-built library as a .so rather than .dylib. Fixing that still doesn't fix the test:
```
ok 1 - nm returned a non-error status
not ok 2 - /sw/build.build/libmaxminddb-1.3.2-1/libmaxminddb-1.3.2/t/../src/.libs/libmaxminddb.0.dylib exports only MMDB_ symbols
#   Failed test '/sw/build.build/libmaxminddb-1.3.2-1/libmaxminddb-1.3.2/t/../src/.libs/libmaxminddb.0.dylib exports only MMDB_ symbols'
#   at ./external_symbols_t.pl line 86.
#     Structures begin differing at:
#          $got->[0] = '_MMDB_aget_value'
#     $expected->[0] = Does not exist
```
because it also doesn't know that darwin prefixes symbols with "_". Note that all of these details are automatically detected by ./configure, but the .t instead hard-codes one platform's details). Fixing that issue also (changing "MMDB_" to "_MMDB_" in that .t) gets a self-test that passes.

**Comment by dmacks** [comment]
Cross-reference: [Issue #168 at upstream libmaxminddb](https://github.com/maxmind/libmaxminddb/issues/168)

**Comment by wodev** [comment]
@dmacks thanks for the first review and the suggestions.
The latest commit 55f5d48 addresses the requested changes.

I have chosen the section:lib because the geoip packages is also there and the new package is for geoip2 database files. In my opinion the database section is not optimal because it is not regular database. The freebsd ports using the net section (specialised for IP address geo lookup) .  Please let me know, if i should move the package into the section:net . 

the chosen name is identical to the upstream project name from MaxMind and the binary is only a command line test tool for IP geo lookups.

**Comment by wodev** [comment]
Commit 3e990f0 corrects the man page and moved the package to the net section.

**Pull request merged**
