### PR TITLE
Lapack cleanup

### PR DESCRIPTION
**Pull request by dmacks**
We have a lot of lapackXXX, only two of which are still in use and many of which use old gccX. Here I switch all to gcc9 and kill off the headers packages for the unused versions. For the latter, the -shlibs are kept per policy. But I masked them out of the 10.15 where they were uncompilable due to (formerly) using a gccX that wasn't available there. And I inverted the .info layout so that -shlibs was the main package in all cases to make it easier to turn off the headers pkgs and minimize the diff among those files.

### CODE REVIEW

**Comment by dmacks** [comment]
Oops, didn't realize another PR touched one of the files in a way that blocked the merge:)

**Comment by dmacks** [comment]
lapack350 is still in use by a ton of octave packages...working on it...

**Comment by dmacks** [comment]
Other tickets that are tracking lapack* packages: #481, #482, #483, #484, #489

**Comment by remkos** [comment]
Feel free to do with lapack packages as you please. I have just handed them in (PR #507).

**Comment by dmacks** [comment]
rebased on master (PR #507 changed Maintainer fields)

**Pull request merged**
