### PR TITLE
Updates gmt-4.5.17 and gmt5-5.4.3, plus change of maintainer (Kurt to…

### PR DESCRIPTION
**Pull request by remkos**
… Remko)

### CODE REVIEW

**Comment by nieder** [comment]
Can gmt/gmt5 work with the package libpcre2, or does it still need libpcre1?

**Comment by remkos** [comment]
GMT code could be made compatible with libpcre2, but it is coded with the older API (of libpcre1). From the (sparse) libpcre web pages, I do not think libpcre2 has any backward compatibility build in, so it would require adjusting the libpcre calls.
(As one of the maintainers of GMT, I can certainly look into that).

**Comment by remkos** [comment]
By the way, gmt5 depends on libpcre1. The package gmt does not depend on libpcre1.

**Comment by nieder** [comment]
If it needs recoding to work with pcre2, it doesn't matter for this submission then.

**Pull request merged**
