### PR TITLE
Simplejson py update

### PR DESCRIPTION
**Pull request by khorton**
Update simplejson-py to latest upstream version.  Builds on macOS 10.13 with fink -m.

### CODE REVIEW

**Comment by nieder** [comment]
Is it worth adding a py36 variant?
Also, should tests be activated?
````
InfoTest: <<
	TestScript: %p/bin/python%type_raw[python] setup.py test
<<
````

**Comment by khorton** [comment]
I see no reason to avoid py36, and tests make sense too.

I’m not sure what the process is now.  Do I make those changes and send another pull request, or will you make them?

Thanks,

Kevin

**Comment by nieder** [comment]
If you do work on your local `simplejson-py_update` branch used for this PR and make fresh commits there, as soon as you push those commits to your remote repository, then this PR will automatically be updated with those new commits.

**Comment by khorton** [comment]
> On Mar 7, 2018, at 06:49 , nieder <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> If you do work on your local simplejson-py_update branch used for this PR and make fresh commits there, as soon as you push those commits to your remote repository, then this PR will automatically be updated with those new commits.
> 
> 

I made those changes, tested them and committed them from my local machine, on the simplejson-py_update branch and finally did a “git push”.  

Thanks,

Kevin

**Comment by dmacks** [comment]
I think the TestScript line should end with ```|| exit 2``` so that fink interprets a failure as a fail/abort rather than a warn/continue.

**Pull request merged**
