### PR TITLE
peakutils-py: new python lib for peak fitting.

### PR DESCRIPTION
**Pull request by kamischi**

### CODE REVIEW

**Comment by dmacks** [comment]
Same ``` || exit 2``` needed?

**Comment by kamischi** [comment]
Sorry, for not noticing. Where would fink be without your care.

**Comment by kamischi** [comment]
Ouch. This turns out to be a bigger problem. I checked with py27 and py36 and assume the same problem with the other py3X. The test of peakutils-pyXX needs panda-pyXX, which depends on numexpr-pyXX, which in turn fails to build on 10.13, at least on my system. So, this needs to wait until numexpr-pyXX is fixed. I'll file a bug report on numexpr within days.

**Comment by dhomeier** [comment]
You can find a workaround for `numexpr-py` in #121, or I could submit a patched .info. But with `pandas-pyXX` installed I still get a test failure
```
/sw/bin/python2.7 setup.py test
running test
running egg_info
writing requirements to PeakUtils.egg-info/requires.txt
writing PeakUtils.egg-info/PKG-INFO
writing top-level names to PeakUtils.egg-info/top_level.txt
writing dependency_links to PeakUtils.egg-info/dependency_links.txt
reading manifest file 'PeakUtils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_*'
writing manifest file 'PeakUtils.egg-info/SOURCES.txt'
running build_ext
/sw/lib/python2.7/site-packages/subprocess32.py:472: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
test_conditioning (tests.peakutils_test.Baseline) ... ERROR
test_centroid (tests.peakutils_test.Centroid) ... ok
test_centroid2 (tests.peakutils_test.Centroid) ... ok
test_peaks (tests.peakutils_test.FBGPeaks) ... ok
test_float64_high_thres (tests.peakutils_test.Float64) ... ok
test_float64_low_thres (tests.peakutils_test.Float64) ... ok
test_int_high_thres (tests.peakutils_test.Float64) ... ok
test_int_low_thres (tests.peakutils_test.Float64) ... ok
test_gaussian_fit (tests.peakutils_test.GaussianFit) ... ok
test_interpolate_bounds (tests.peakutils_test.InterpolateExceptions) ... ok
test_peaks (tests.peakutils_test.LPGPeaks) ... /sw/lib/python2.7/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)
/sw/lib/python2.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
ok
test_plateau1 (tests.peakutils_test.Plateau) ... ok
test_plateau2 (tests.peakutils_test.Plateau) ... ok
test_scale (tests.peakutils_test.Prepare) ... ok
test_scale_degenerate (tests.peakutils_test.Prepare) ... ok
test_list_peaks (tests.peakutils_test.SimulatedData) ... ok
test_near_peaks1 (tests.peakutils_test.SimulatedData) ... ok
test_near_peaks2 (tests.peakutils_test.SimulatedData) ... ok
test_pandas_series (tests.peakutils_test.SimulatedData) ... ok
test_peaks (tests.peakutils_test.SimulatedData) ... ok

======================================================================
ERROR: test_conditioning (tests.peakutils_test.Baseline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/peakutils-py27-1.0.4-1/PeakUtils-1.0.4/tests/peakutils_test.py", line 117, in test_conditioning
    data = data = load('exp')
  File "/scratch.noindex/fink.build/peakutils-py27-1.0.4-1/PeakUtils-1.0.4/tests/peakutils_test.py", line 14, in load
    return numpy.loadtxt(p)
  File "/sw/lib/python2.7/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/sw/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/sw/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: /scratch.noindex/fink.build/peakutils-py27-1.0.4-1/PeakUtils-1.0.4/tests/exp not found.

----------------------------------------------------------------------
Ran 20 tests in 0.101s

FAILED (errors=1)
```
That's really an upstream bug, since the `exp` datafile is missing from the tarball. You might download it as a `Source2` from the bitbucket repo or try to disable that test.

Also, `scipy-py` needs to go into the main `Depends:`
```
Python 2.7.15 (default, May 12 2018, 03:12:03) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import peakutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python2.7/site-packages/peakutils/__init__.py", line 1, in <module>
    from .baseline import *
  File "/sw/lib/python2.7/site-packages/peakutils/baseline.py", line 4, in <module>
    import scipy.linalg as LA
ImportError: No module named scipy.linalg
```
-- that will cover numpy as well, which is also a runtime dependency.

On the formal side, one could discuss whether the package better fits into the `sci` category.

**Comment by kamischi** [comment]
Isn't this fine now?

**Comment by nieder** [comment]
There's no pandas-py37 yet. But this built/tested fine on py27-36.

**Comment by nieder** [comment]
The py37 variant needs to be removed for now due to missing dependencies. The indirect dependency [pytables fails to build as py37](#317 ).

**Comment by nieder** [comment]
tested/passed py27-36 on 10.13

**Pull request merged**
