### PR TITLE
IPython / Jupyter-notebook infrastructure

### PR DESCRIPTION
**Pull request by dhomeier**
This is an ongoing attempt to put together the umpteen packages required for the current upstream versions of IPython (5.4/6.2) and (Jupyter-)Notebook (5.4), providing some core dependencies like `ipython-genutils` and `ipykernel` and numerous smaller new packages or updates of same.
Building and especially testing the whole ecosystem suffers from a number of circular dependencies; at this point I've updated everything that should be required to upgrade to the new `jupyter-core` and `jupyter-client` and `nbconvert`.
The main challenge is that `ipykernel` only builds with a working `ipython` installed, while the other packages can be (partially) built without `ipykernel`, but some or all tests will fail. As upgrade path I therefore suggest
```
fink -m update dateutil-pyXX traitlets-pyXX zmq-pyXX
fink --validate update jupyter-core-pyXX jupyter-client-pyXX
fink -m update entrypoints-pyXX nbformat-pyXX pygments-pyXX testpath-pyXX
fink --validate update nbconvert-pyXX
```
Feedback desired, cherrypicking missing packages e.g. for #139 welcome.

### CODE REVIEW

**Comment by dhomeier** [comment]
Should be everything required for the `ipython` update at this point; afterwards `ipykernel` can be built and then the packages first built without tests verified:
```
fink -m update pickleshare-pyXX prompt-toolkit-pyXX ipywidgets-pyXX
fink --validate validate ipython-pyXX
fink -m update ipykernel-pyXX
fink -m rebuild jupyter-core-pyXX jupyter-client-pyXX nbconvert-pyXX ipython-pyXX
```

**Comment by dhomeier** [comment]
The versioned 5.7.0 was intended for the long-term support for Python 2.7 (although the minor release numbers still seem to be incremented fairly regularly), `ipython-py` would be for the latest upstream (currently 6.4.0), see next commit coming up. Of course we can also keep the 3.x branch around in a versioned file (there is a `3.2.3` release though, and a whole series `4.0.0-4.2.1`), with a `Conflicts: path-py (>= 10.0-1)`.

**Comment by dhomeier** [comment]
Though I wouldn't know how to build the older version with fink once the newer `.info` is in place - only `apt-get install`ed legacy stuff so far...

**Comment by nieder** [comment]
How does one start committing (cherry picking) individual commits from here to simplify the master diff? For example, baae7a7 doesn't have any other new deps.

**Comment by dhomeier** [comment]
I don't have any experience with cherrypicking as such, but clearly baae7a7 would be a possible start (which set it all off in #139). Taking the entire commit history up to `ipykernel`, `jupyter-core` or jupyter-client` (752357f) might also work.

**Comment by nieder** [comment]
The good news is that I can cherry pick directly into master using SourceTree and push individually to origin from there (baae7a7 and 5d9e6a7) The bad news is that it's not being reflected in the diff when viewed here in the PR. The commits are showing up with different hashes in master, so maybe that's why it can't track them?
@dmacks I've seen you do individual cherry picks. What was your procedure?

**Comment by nieder** [comment]
Testing 8a2b33a (ipykernel-pyXX), I get this error:

````
ipykernel-4.8.2/setup.cfg
ipykernel-4.8.2/setup.py
sudo -u fink-bld [ENV] sh -c /tmp/fink.V0j_Q
python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
  File "/sw/build.build/ipykernel-py27-4.8.2-1/ipykernel-4.8.2/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/sw/build.build/ipykernel-py27-4.8.2-1/ipykernel-4.8.2/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named IPython.core.profiledir
### execution of python2.7 failed, exit code 1
````
I do not have ipython-py (3.2.1-2 from stable) installed.

**Comment by nieder** [comment]
I understand. I'll go forward with testing the [above build path](https://github.com/fink/fink-distributions/pull/164#issuecomment-389359893). !lart things that need their own dependees.

For the ipython 5.7.0 version: is there a reason to keep py35 and py36 variants of it since those will be available in the 6.x series? If there isn't a need to keep the 5.7-py3X, then ipython-5.7.0.info can instead be called ipython-py27.info and there won't be .info naming issues if a new release is made in the 5.x series. Thoughts?

**Comment by dhomeier** [comment]
Yes, that would be a good option, as development on 5.x is obviously continuing. I had only kept the Python 3 variants as a backup in case something turned out to be broken in ipython 6.x, but since this is well past 6.0 now, that does not appear to be the case.

**Comment by nieder** [comment]
Building jupyter-core-py27 (`fink --validate update jupyter-core-py27`):
````
#!/bin/bash -ev
 find . ../jupyter_core  -name __pycache__ -or -name '*.py[oc]' -exec rm -r {} \;
find: ../jupyter_core: No such file or directory
````

**Comment by dhomeier** [comment]
Sorry, missed updating the change in `cwd` when I moved the cleanup from `TestScript` to `InstallScript`.

**Comment by dmacks** [comment]
I notice some TestScript have ```|| exit 1```, which makes fink treat test-suite failures as warnings, some have ```|| exit 2``` (test-suite failures treated as failures), and some have no shell exit-code control. That last category is not clear as to your intended effect (I assume it's equivalent to exit=1?). The exit=1 case is reasonable for where you have expected failures, although it would be even better if those specific tests could be disabled. Or else could you have a user-visible ```echo "some test failures expected: [list them]``` so when users see a failure that is then ignored, they don't get confused or whiny:)

**Comment by dhomeier** [comment]
Updated `TestDepends`, seems I haven't tested install independently of `nbconvert`.

**Comment by dhomeier** [comment]
@dmacks, sometimes I've taken over the test return codes from previous package versions, otherwise my priority was to at least have some test coverage, as there were/are many packages without any `TestScript` at all. Yes, the standard python return  from failed tests is 1 (not 100% sure about direct calls of `pytest` or `nosetests`); might be 2 above a certain number of `Fail`/`Error`s - at least one can tweak the python call to return this.
I am less concerned about scaring users who actually build with `-m`, in most cases the error messages are already out of sight once the install phase is completed, but as @nieder has already commented, accepting failed tests might mask new errors that could pop up at a later time. I will try to rebuild everything and change the test returns to `exit 2` where possible, when I have some time.

**Comment by dhomeier** [comment]
Superseded by #391 and #413.

**Pull request closed without merging**
