### PR TITLE
Texi2html onboard perl

### PR DESCRIPTION
**Pull request by dmacks**
Creating a private perl5162 interpretter (hidden in lib/texi2html) for texi2html to use on platforms where apple doesn't supply perl5162 and we don't feel like having to continue supporting a full user-land perl5162 suite. See PR #339.

### CODE REVIEW

**Comment by dmacks** [comment]
Note, this isn't actually *tested* on 10.14 as I only have a 10.13 fink sandbox at the moment...

**Comment by kamischi** [comment]
with an unmodified 10.14, building breaks with:
...
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nieder** [comment]
Is it texi2html that fails building or the private perl (texi2html-perl5162)?

**Comment by kamischi** [comment]
private perl.

**Comment by dmacks** [comment]
grr. Depending on weather and everyone's health in my house, I might be able to get to a 10.14 machine starting tomorrow to work on it for real.

**Comment by nieder** [comment]
@kamischi can you look in the build output for `What command should be used to create dynamic libraries?` and paste the output from that query and the next two?

**Comment by nieder** [comment]
On my 10.14 VM, texi2html-perl5162 built fine/passed tests. And the linker is passed `-mmacosx-version-min=10.14` as expected with the patch. texi2html-1.82-203 also built, and perl5162-core is not installed.

**Comment by nieder** [comment]
Another positive report for texi2html-perl5162 on Fink-beginners: https://sourceforge.net/p/fink/mailman/message/36590638/

**Comment by dmacks** [comment]
Given a few positives and no details about the fail, and that it (at least sometimes) fixes a hard blocker for many 10.14 users, should we push this as (at worst) a stop-gap solution pending further improvement?

**Comment by nieder** [comment]
Concur.

**Comment by nieder** [comment]
I guess we now need to mark all 5162 perlmods as !10.14

**Comment by dmacks** [comment]
Won't see me crying...

**Pull request merged**
