### PR TITLE
ffmpeg upgrades

### PR DESCRIPTION
**Pull request by dmacks**
This switches all ffmpeg3 users to ffmpeg4.

### CODE REVIEW

**Comment by dmacks** [comment]
New upstream version ffmpegthumbnailer builds if you apply some upstream patches (dirkvdb/ffmpegthumbnailer#179) which requires a updated version of cmake (PR #555)

**Comment by nieder** [comment]
@htodd pianobar is yours. Seems OK since it's only a version bump on libav* dependencies with no patching needed.

**Comment by htodd** [comment]
Sounds good to me.

**Comment by htodd** [comment]
I think I clicked the wrong button.

**Comment by htodd** [comment]
I hate github (as I said before) and I'm not sure what I'm supposed to
click on.

On Wed, 8 Jan 2020, nieder wrote:

> 
> @htodd pianobar is yours. Seems OK since it's only a version bump on libav* dependencies with no patching needed.
> 
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AANLE446PAJSOG7AIQD4J5DQ4W37TA5CNFSM4KDOHKZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIMDVUA.gi
> f]
> 
> 
>

-- 
Hisashi T Fujinaka - htodd@twofifty.com
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by nieder** [comment]
In the "Files changed" tab, click the "Review Changes" button (towards upper right) and select the review you want to provide ("approve" in this case).

**Pull request merged**
