### PR TITLE
Texlive2023

### PR DESCRIPTION
**Pull request by nieder**
This updates to texlive-2023.
Fails a couple tests, but no idea why. Can be ignored since it's something about those 4 characters it doesn't like.
```
[ in texk/web2c ]
FAIL: uptexdir/upbibtex
=================
<snip>
Database file #7: enc-amb1.bib
diff $srcdir/tests/enc-up.bbl uptests/xenc-u0-e.bbl || rc=62
+ diff ../../../texk/web2c/tests/enc-up.bbl uptests/xenc-u0-e.bbl
8,9c8,9
< \item C2Ax: ￠￡￥§¨￢
< \item C2Ax: ￠￡￥§¨￢
---
> \item C2Ax: ¢£￥§¨¬
> \item C2Ax: ¢£￥§¨¬
+ rc=62


exit $rc
+ exit 62
FAIL uptexdir/upbibtex.test (exit status: 62)

FAIL: uptexdir/nissya
=====================
<snip>
Database file #1: sample.bib
  diff $srcdir/ptexdir/tests/nissya_bib.bbl uptests/nissya_bib.bbl || exit 2
+ diff ../../../texk/web2c/ptexdir/tests/nissya_bib.bbl uptests/nissya_bib.bbl
46c46
<   『非定型データのコーディング・システムとその利用』平成8年度～10年度科学研究費補助金(基盤研究(A)(1))(課題番号 08551003)研究成果報告書,\hspace{.6em}大阪大学．
---
>   『非定型データのコーディング・システムとその利用』平成8年度〜10年度科学研究費補助金(基盤研究(A)(1))(課題番号 08551003)研究成果報告書,\hspace{.6em}大阪大学．
+ exit 2
FAIL uptexdir/nissya.test (exit status: 2)
```
```
[ in texk/dviout-util ]
FAIL: dvispc
============
<snip>
# ==== TeX Live specific start ====

## EXE2TEXT + EXE2DVI: check for -J option

./dvispc -a -Ju $testdir/jisx0208.dvi jisx0208.da.txt || exit 2
+ ./dvispc -a -Ju ../../../texk/dviout-util/tests/jisx0208.dvi jisx0208.da.txt
$DIFF $testdir/jisx0208.txt jisx0208.da.txt || exit 1
+ diff ../../../texk/dviout-util/tests/jisx0208.txt jisx0208.da.txt
45,46c45,46
< set2 0x2141 "～"
< set2 0x2142 "∥"
---
> set2 0x2141 "〜"
> set2 0x2142 "‖"
76c76
< set2 0x215d "－"
---
> set2 0x215d "−"
96,97c96,97
< set2 0x2171 "￠"
< set2 0x2172 "￡"
---
> set2 0x2171 "¢"
> set2 0x2172 "£"
137c137
< set2 0x224c "￢"
---
> set2 0x224c "¬"
+ exit 1
FAIL dvispc.test (exit status: 1)
```

### CODE REVIEW

**Comment by dhomeier** [comment]
Same result on 12.7; my 2d on the 2¢ would also be should be no serious problem; looks like somehow different sets of UTF characters are used.

**Comment by nieder** [comment]
Looking at https://www.alt-codes.net/cent_alt_code.php and pasting things there to see visually:

image

The input cent sign (bigger C with angled line on my system) matches the `&#65504;` code, while `&#162;` matches the output code. The test reference file only has the initial commit, and it's not obvious from it why they chose the really high Unicode characters versus the more normal range. Should work to generate a patch to have the reference with the lower characters.

**Comment by nieder** [comment]
564a3b0 fixed things for me.

**Comment by nieder** [comment]
Now passes tests for me. Please review

**Review by dhomeier — APPROVED** [review]
Passing all tests on 14.2.1 as well!

**Pull request merged**
