### PR TITLE
zmq-py, libzmq6: update, add py37 variant

### PR DESCRIPTION
**Pull request by kamischi**
the new version needs libsodium23, which is in its own update branch.

zmq-py: update source URL.

### CODE REVIEW

**Comment by maartanis** [comment]
With libsodium23 being merged to master, this pull request can be reviewed.

**Comment by nieder** [comment]
ping @schwehr

**Comment by dhomeier** [comment]
LGTM, all variants build and pass validation. 2 comments:
1. The license is now given as "BSD License, GNU Library or Lesser General Public License (LGPL) (LGPL+BSD)", and both `COPYING.BSD` and `COPYING.LESSER` are included. I think changing the field to `License: OSI-Approved`

2. Any chance to get the tests enabled?
```
# 11-24 test failures; exclude potentially hanging tracker test under 2.7
InfoTest: <<
  TestDepends: pytest-py%type_pkg[python]
  TestScript: <<
    PYTHONPATH=%b/build/lib %p/bin/pytest-%type_raw[python]  -vk 'not test_tracker' zmq/tests || exit 1
  <<
<<
```
The tracker is failing under Python 3 as well, so we may as well disable it altogether...
```
>       assert p1 is zmq._FINISHED_TRACKER
E       AssertionError: assert <zmq.sugar.tracker.MessageTracker object at 0x105cdff28> is <zmq.sugar.tracker.MessageTracker object at 0x10573ba90>
E        +  where <zmq.sugar.tracker.MessageTracker object at 0x10573ba90> = zmq._FINISHED_TRACKER
```

**Comment by dhomeier** [comment]
OK, actually managed to push to this branch; hopefully without breaking anything. I've pondered adding the examples/ directory to `DocFiles`, see comments on the `pyzmq-py3k-examples` in the new .info.

**Comment by kamischi** [comment]
I included the test sources for python3. The tests fail with:

ImportError: cannot import name 'constants'

I found that in buildutils, but no idea, how to tell python the location.

**Comment by nieder** [comment]
We should version the libzmq6 (Build)Depends to >= 4.2.5:
````
    ZMQ version detected: 4.1.3
Warning: Detected ZMQ version: 4.1.3, but pyzmq targets ZMQ 4.2.5.
````
py27 tests don't even start with the `cannot import name 'constants'` error.
And I also get the same 11 test failures on py35. And upgrading to latest pyzmq doesn't fix any of them.

**Comment by dhomeier** [comment]
I've pushed the updates since the new libzmq fixes some vulnerabilities.

**Comment by kamischi** [comment]
All fine with me.

**Comment by nieder** [comment]
This lets libzmq6 pass tests:
````
InfoTest: <<
	TestScript: ulimit -n 1200; make check || exit 2
<<
````
I also got zmq-py27/37 to pass tests. I'll post the cleaned change up tonight.

**Comment by nieder** [comment]
This combo of *Script: passes all tests for all pyXX variants:
````
CompileScript: <<
  %p/bin/python%type_raw[python] setup.py build_ext --inplace --zmq=%p
<<
InstallScript: %p/bin/python%type_raw[python] setup.py install --root=%d
InfoTest: <<
  TestDepends: pytest-py%type_pkg[python]
  TestScript: <<
    #!/bin/sh -ev
    if [ %type_pkg[python] -gt 30 ]; then
      cp -R ../pyzmq-py3k-examples-master/* examples/
    fi
    %p/bin/python%type_raw[python] setup.py test --zmq=%p || exit 2
  <<
<<
````

**Pull request merged**
