### PR TITLE
Updated Monotonic to include Python 3.9 and 3.10

### PR DESCRIPTION
**Pull request by sth0**
Added python 3.9 and 3.10 to the available python versions for monotonic

### CODE REVIEW

**Review by nieder — CHANGES_REQUESTED** [review]
Homepage field points to wrong package.
Any chance you can update to v1.6 (from 2021 vs 1.5 from 2018)?

**Comment by sth0** [comment]
Will adjust package.  Not sure if the update is possible without breaking a lot of things, there was an issue with some utilities.  Didn't check the homepage, since I didn't modify it, will correct.

**Comment by sth0** [comment]
Updated per suggestions

**Review by nieder — APPROVED** [review]
LGTM.
FYI, upstream has archived this project, so 1.6 looks to be the final release.

**Pull request merged**
