### PR TITLE
Libcurl upgrades

### PR DESCRIPTION
**Pull request by dmacks**
Continuating work from "[Fink-users] Update to cURL?"

### CODE REVIEW

**Comment by sth0** [comment]
Haven't managed to send a pull request, but here is the edit I added and it seems to compile and test.

 
 	#Set up to use system's ldap
+	#I think the xcrun will work on systems back to kernel
+	# version 15 (MacOSX 10.11 El Capitan) - sth
 	InclPREFIX="/usr/include"
 	if [ "$(uname -r | cut -d. -f1)" -ge 18 ]; then
-		InclPREFIX="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
+		InclPREFIX="`xcrun --sdk macosx --show-sdk-path`/usr/include"
 	fi

**Comment by sth0** [comment]
Compiles and passes test MacOS 13.6.3-X86 / Xcode 15.2 / CLT 15.1

**Comment by sth0** [comment]
I this ready to merge?  Are there issues?

**Comment by dmacks** [comment]
Upstream has newer versions now. But the main focus here is reducing the spaghetti by using fink's dap. So may as well get this thing merged...

**Pull request merged**
