### PR TITLE
Ffmpeg upgrades older

### PR DESCRIPTION
**Pull request by dmacks**
This switches all ffmpeg2 users to ffmpeg4.

### CODE REVIEW

**Comment by dmacks** [comment]
video-oct is akh's; mpd is Jack Fink's (can't find him on github?); all the rest are Nieder's.

@nieder with this and PR #554, the two older ffmpeg suites are completely unused, so you could knock libavcodec56-2.4-shlibs.info and libvcoded57-3.0-shlibs.info down to -shlibs stubs.

**Comment by nieder** [comment]
These look reasonable to me.
Waiting on @akhansen for video-oct, then can commit

**Comment by akhansen** [comment]
I'm good with the change in video-oct364.  Mind unmaintaining it for me?

**Comment by dmacks** [comment]
Per previous comments, let's mkitso.

**Pull request merged**
