### PR TITLE
migrate wgscott packages to gcc9

### PR DESCRIPTION
**Pull request by nieder**
This is for #481 to close down gcc5.

There are upstream bumps for some packages (coot, mmdb2, libccp4), but I didn't follow them.

### CODE REVIEW

**Comment by dmacks** [comment]
By eye, this looks sane (and also switched to newer boost, which is a Good Thing). I suspect some of the dependencies on "gcc9" could be reduced to "gcc9-compiler" but that shouldn't hold up getting this stuff committed...set a week timer?

Can PR #124 be merged into here?

**Comment by dmacks** [comment]
Can these upgrade from fftw to fftw3? That would push out an old-version dep that is itself gcc5 (unmaintained).

**Comment by nieder** [comment]
re: fftw
Not simply. At least one of them (coot?) was looking for -lsfftw, which does not have a direct replacement in fftw3. Others might be OK, but I wanted to keep the stack consistent.

**Comment by dmacks** [comment]
Good idea. Might want to add a link to https://www.mail-archive.com/coot@jiscmail.ac.uk/msg00336.html to explain this intentional unusual linking.

**Comment by dmacks** [comment]
These are just build/dep updates, not new versions...let's unblock these on new OSXen.

**Comment by dmacks** [comment]
coot still has Depends:gcc5.

**Pull request merged**
