### PR TITLE
R-base 4.1: Patch ATSFont calls to CGFont calls, update gcc11 to gcc12

### PR DESCRIPTION
**Pull request by sth0**
R-base4.1 does not compile on MacOS 13.  This OS release removed the deprecated ATSFont calls for the newer CGFont calls.  This replaces the calls with the corresponding new API.  Also updated the link to gcc12-shlibs from gcc11-shlibs.

### CODE REVIEW

**Comment by nieder** [comment]
R packages that use gccXX hardcode the version that R-base was built against. Which is why you see lines like this:

https://github.com/fink/fink-distributions/blob/60fcd1badf9c742f90fe5064bfb2961865653818/10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-tidyr-r.info#L57

If we update r-base41 to gcc12, then we have update all relevant cran-XXX-r41 packages to use gcc12 (apart from gccXX availability issues across macOS versions).

**Comment by sth0** [comment]
Will regress to gcc11-shlibs

**Comment by sth0** [comment]
I have been using the PR #1080 <https://github.com/fink/fink-distributions/pull/1080> which seems to allow building of gcc11 / 12 / 13 on all the systems I have tried.

**Comment by sth0** [comment]
pushed commits to regress to gcc11 compiler and bumped revision number.

**Comment by dmacks** [comment]
This patch looks like upstream's https://bugs.r-project.org/show_bug.cgi?id=18426 so we should cite it as such in the .info (might be cleaner to have that attachment literally as a PatchFile2 instead of merged into the main PatchFile).

**Comment by sth0** [comment]
I had trouble applying it as a separate patch and thus combined it.  I can try to separate them out as separate patches if the consensus is that is "cleaner".

**Comment by dmacks** [comment]
Doesn't really matter whether it is a seperate .patch or not, whatever is easier. But if that's the origin of the patch, definitely need to document that fact in the .info.

**Comment by sth0** [comment]
Will update the implementation description.

**Comment by sth0** [comment]
Added comment to BuildDesc tag and removed references to PCRE1 which is not used for R version 4.1

**Pull request closed without merging**
