### PR TITLE
Updates for rpy2-py building against R3.4

### LINKED ISSUE #17: R version support
Spawning a new topic from #12, wherein:

@dmacks:
>We currently use a Distribution tag to limit r-base32 to 10.{9-12}, but we don't limit any other r-base*. Should we similarly restrict r-base31? Do we even need to keep dragging r-base33 along, or is r-base34 sufficient to keep going forward?

@nieder:
>Personally, I don't know if there's any reason to keep r33 since I think most rmods that use r33 are available as r34. There are some in r31 that are not available in later releases (but I would imagine that's most likely because they're abandoned).

Here, let's figure out what rmods need to be brought forward vs be marked "do not bring forward" (so we don't have to have this conversation again in the future), and then whether to drop r31 and/or r33 on 10.13....

### PR DESCRIPTION
**Pull request by dhomeier**
Update to 2.8.6 (last version with Python 2.7 support) and 2.9.1
(for the Python 3.x types); upgraded R dependencies to 3.4 to help resolve #17.
Tested and built on 10.12 and 10.13; note that some of the tests use pandas-py*, if present.
The 2.9.1 version (`rpy2-py.info`) may need an update of `cran-dplyr-r34` to 0.7.4 (at least for the tests), but I haven't upped the Depends yet.

### CODE REVIEW

**Comment by dmacks** [comment]
The version-bump and migration to r34 in rpy2-py.info looks fine. Is the goal of the new rpy2-py-2.8.6.info file because the new version (2.9.1) does not support python27, so we keep the last 2.8.x for older python? If that's the situation, is it useful to still have python3x as variants for it, which would be masked by the newer .info?

**Comment by dhomeier** [comment]
Yes, `2.8.6` is required for python27-compatibility; I just kept the py3x variants in case anyone wanted the exact same version for some reason, but there is probably no real use case (and I guess for e.g. `apt-get install rpy2-py36=2.8.6-1` to work one would have to incrementally update first to 2.8.6 and then to 2.9.x for the package to be built in the first place)...
I submitted another update to the now-current 2.9.2 from upstream; found that the tests require a bunch of updates to various R modules, but with those in place, should all succeed (see `DescPort`, tested on 10.12 and 10.13).

**Comment by dhomeier** [comment]
@dmacks, I've updated `rpy2` again to the current upstream and added a new package now required by its `pandas` loader. See `DescPort` for remaining issues when running the tests.

**Comment by dmacks** [comment]
Some of the cran mods look like they have incorrect Distribution tags for their langversion types. If you supply -r31, you need to make sure it's only for 10.9-10.12 (not 10.13). In a few of your commits, you removed the Dist tags for r31, which makes it visible on all platforms (even 10.13).

**Comment by nieder** [comment]
I cherry picked the new-to-fink tzlocal-py and cran-dbplyr-r commits from here into the main tree. All the other included deps (glue, purrr, etc) had been updated independently past what this PR did so they all have git conflicts. rpy2-py also has git conflicts. I'm going to close this because it's going to be a mess to fix the git tangle and it'll be cleaner and easier to understand to go with a fresh start at updating rpy2-py.

**Pull request closed without merging**
