### PR TITLE
arm64/aarch64 build fixes for nettle7 and libid3tag

### PR DESCRIPTION
**Pull request by dhomeier**
Separating the packages addressed in #952 out here.
`libid3tag` works as proposed with updated `config.guess` (tested on old 10.14 installation with fink 0.45 and dpkg 1.10.21 as well). Both are building as `aarch64-apple-darwin...` now.
`nettle8` from ab0978d builds without further changes.

### CODE REVIEW

**Comment by TheSin-** [comment]
I think the nettle7 fix is likely the best option.  I'll have to cherry pick it though cause I'm not going to test libid3tag.  Hopefully I'll get it in today as I need to get python27 in today

**Review by sth0 — APPROVED** [review]
LGTM

**Comment by TheSin-** [comment]
Seems, this isn't enough

```
/usr/bin/install -d -m 755 /opt/sw/src/fink.build/root-nettle7-3.5.1-3/opt/sw/share
/bin/mv /opt/sw/src/fink.build/root-nettle7-shlibs-3.5.1-3/opt/sw/share/info /opt/sw/src/fink.build/root-nettle7-3.5.1-3/opt/sw/share/
mv: rename /opt/sw/src/fink.build/root-nettle7-shlibs-3.5.1-3/opt/sw/share/info to /opt/sw/src/fink.build/root-nettle7-3.5.1-3/opt/sw/share/info: No such file or directory
```

seems a missing dep maybe?  I'm looking into it.

```
  Documentation:     no
```

```
checking for makeinfo... not-found
```

need a BD on `texinfo`

Once tested I'll commit nettle7 with this patch and the BD addition

**Comment by dhomeier** [comment]
> need a BD on `texinfo`

Ah, of course; same as for `nettle8` (at least on Ventura, <= 12.x still has its own makeinfo, but better to use the same build everywhere).

**Comment by nieder** [comment]
I think these are fixed. Just updated libid3tag and nettle7 was fixed in 6c2b7df

**Pull request closed without merging**
