### PR TITLE
Htodd fdupes

### PR DESCRIPTION
**Pull request by htodd**
Adding new package for fdupes.

### CODE REVIEW

**Comment by nieder** [comment]
What's the purpose of the `Replaces: %{ni}` and `Provides: fdupes` fields?
Also, don't need to `BuildDepends:` on `fink (>= 0.24.12-1)` any more. All supported distributions have only had fink greater than that version.

**Comment by htodd** [comment]
My mistake. I used another info file as an example and I never know what to keep. I'll fix that.

**Comment by nieder** [comment]
Forgot to notice: There's a BDep on fink-package-precedence, but it's not used in CompileScript.

**Comment by nieder** [comment]
I would add a check with f-p-p to CompileScript (or to the very beginning of InstallScript so that you don't have to add to the default CompileScript). Important since this uses ncurses and we want to make sure to not accidentally grab system-ncurses.

**Review by nieder — APPROVED** [review]
fdupes looks good. not sure how bowtie2 and vim made it into the branch, but shouldn't affect merging.

**Pull request merged**
