### PR TITLE
Various updates to NetCDF and HDF5 dependencies

### PR DESCRIPTION
**Pull request by remkos**
This PR updates the following dependencies:
netcdf-c13 -> netcdf-c15
hdf5.10 -> hdf5.100.v1.10
hdf5-cpp11 -> hdf5-cpp.100.v1.10

In the following packages:
ncview
netcdf-cxx4
gmt5
gmt
gdl

All are built and tested with `fink -m build` on MacOS 10.14.3 with Command Line Tools 10.1

### CODE REVIEW

**Comment by akhansen** [comment]
I recommend using (>>1.10.0-4) for any hdf5.100 dependencies to enforce correct hdf5.h detection.

**Comment by remkos** [comment]
@akhansen: Done in commit 963fb01 as per your apt suggestion

**Comment by PovlAbrahamsen** [comment]
@remkos , if you wish to take over as maintainer of ncview, please do so and remove any reference to me from the info file.

**Comment by remkos** [comment]
ncview: Took over from @PovlAbrahamsen as maintainer. Thanks Povl.
Also added dependency to Fink's libxt as suggested by Povl.

**Comment by nieder** [comment]
**10.13/Xcode9.4**
gdl:
````
[ 19%] Building CXX object src/CMakeFiles/gdl.dir/FMTOut.cpp.o
In file included from /sw/build.build/gdl-0.9.7-4/gdl-0.9.7/src/FMTLexer.cpp:3:
In file included from /sw/build.build/gdl-0.9.7-4/gdl-0.9.7/src/includefirst.hpp:60:
In file included from /sw/include/eigen3/Eigen/Core:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:246:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named
      'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named
      'fpclassify' in the global namespace
using ::fpclassify;
(and many other 'not found in global namespace' errors)
````

**Comment by remkos** [comment]
@nieder: Interesting. This clearly is an Xcode 9.4 issue, as that is where the errors occur.
I had no such problem with 10.14.3 and Command Line Tools 10.1, neither before or after this patch.

What do you suggest I do?
- Remove the `gdl` update from the PR so that at least the others can move forward (alternatively start a new PR)
- Limit this package to 10.14 or more recent Xcode only.
- Find some compiler flag that turns this error into a warning.

**Comment by nieder** [comment]
gmt: OK.
gmt5: OK.
ncview: OK.
netcdf-cxx4: OK.

I tested 0.9.9 and it also fails. I would remove gdl from here and start a separate PR so that the above 4 can be committed.

**Comment by remkos** [comment]
Thanks @nieder for the suggestion.
This PR is now closed and superseded by PR #380

**Comment by dhomeier** [comment]
@remkos, @nieder, I am getting the same errors building `gdl` already with the previous revision on 10.12 and Xcode 9.2. I've seen probably related `clang++` problems due to including the wrong `cmath` header, as the ones in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` and `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain` are crucially different - similar to the issues described [here](https://forums.developer.apple.com/message/263193#263193).

I was able to build the package by removing the SDK path prefix from ZLIBDIR introduced in `0.9.7-3`, changing it to `-DZLIBDIR=/usr/include` - I suggest to make this conditional on the OS or Xcode version, e.g.
```
CompileScript: <<
#!/bin/bash -efv
. %p/sbin/fink-buildenv-helper.sh
if [ $DARWIN_MAJOR_VERSION -ge 18 ]; then
  sdk_inc=`xcrun --sdk macosx --show-sdk-path`/usr/include
else
  sdk_inc=/usr/include
fi
mkdir build
pushd build
%p/bin/cmake \
...
        -DZLIBDIR=$sdk_inc \
```

I also needed to explicitly add `-DHDF5_INCLUDE_DIRS=%p/opt/hdf5.v1.10/include` to the cmake call; otherwise `hdf5.h` was not found.

**Comment by nieder** [comment]
@dhomeier 's plan to conditionalize using the SDK path worked for me on 10.13/Xcode9.4 as well.

**Comment by remkos** [comment]
@dhomeier 's plan is now incorporated in PR #387

**Pull request closed without merging**
