### PR TITLE
Fixed asn1crypto DocFiles for case-sensitive FS, update to 1.4

### PR DESCRIPTION
**Pull request by dhomeier**
Install failed because of a lower-case `readme.md`; also forwarded to latest upstream version.

### CODE REVIEW

**Review by nieder — APPROVED** [review]
LGTM

**Comment by nieder** [comment]
@dhomeier if I push this one, will it mess up the matplotlib PR in #678 ? I notice that the branch `dhomeier:matplotlib2+3` seems to have been created off the `dhomeier:asn1crypto-1.4` branch.

**Comment by dhomeier** [comment]
> @dhomeier if I push this one, will it mess up the matplotlib PR in #678 ? I notice that the branch `dhomeier:matplotlib2+3` seems to have been created off the `dhomeier:asn1crypto-1.4` branch.

My mistake – I just noticed this was also among the 2nd- or 3rd-level dependencies of the `twisted-py` package there, but since I've already found it up to date in my branch, haven't taken any further action.
So I think it should be safe to merge; if any problems arise, I'll try to rebase #678, but I guess that would already be rebased...

**Comment by dhomeier** [comment]
@nieder well, looking closely, e3355bd is already part of #678, so merging that would automatically include it, and I am not 100 % sure what happens if the commit already exists. Should probably work out, but I'd also be fine with just waiting for #678 to be ready, and then closing this one. I guess the case sensitivity problems have never affected anyone but me...

**Comment by nieder** [comment]
My hope was to cherry pick some commits out of #678 to help clean the diff log to make comparisons easier. Sometimes it's easy to get lost in the order of commits since some deps show up after the Depender.

**Comment by dhomeier** [comment]
I am afraid that's become quite hard now after messed-up wxpython400 update. I might try to reset to f740b30 and then push the dependency updates first, then wxpython410, then the actual matplotlib-py38...

**Comment by nieder** [comment]
I'm going to push this to clean some things out. The I can cherry pick some stuff from #678 to minimize the deltas for the more complicated changes.

**Pull request merged**
