### PR TITLE
Add missing variants to pythonmods

### PR DESCRIPTION
**Pull request by dmacks**
These patches add -py35 and -py36 to python modules that were only present in lower -py3X variants. I omitted obsolete ones, and ones that have known issues, PR filed, or are work in progress elsewhere. Is it worth backporting *-py36 to -py35 and -py34 for completeness, or do we not really care about those lower python3X any more? Should one or both be turned off?

Affected maintainers: @bcully, @danielj7, @dhomeier, @khorton, @nieder, Scott Hannahs

### CODE REVIEW

**Comment by nieder** [comment]
typing-py is a backport to -py27 and -py34 of a module included in python35 and up. It should not need being present as -py35 or -py36 variants. It's easy to conditionally Dep on it, so I don't think we need to add py35 and py36 variants and shadow a base module.

It was packaged because newer sphinx will eventually need it.

Other changes to my pymods are OK.

**Comment by danielj7** [comment]
I'm fine with it.

I would only backport from py36 if necessary for a dep hole. Py34 is the oldest version still being supported by upstream but I'd say that if there's no packages that don't work with newer versions, we should get rid of it. Same for py35. 3.7 will be out soon.

**Comment by khorton** [comment]
I have no concern about this change.

Kevin Horton

**Comment by nieder** [comment]
ping @dhomeier @bcully

**Comment by dmacks** [comment]
bb9e529 addresses @nieder's concern. Two more commits cherry-picked from master that add variants as part of a larger set of updates.

**Comment by dhomeier** [comment]
I am absolutely fine with retiring `python3.4`; a number of updates I've pushed still include `py34` variants, but I'd rather remove those in a separate changeset.
For `py35` I am still seeing 32 packages without a `py36` counterpart; although many of them already have updates under way, I vote for keeping `python3.5` around for now.

**Comment by bcully** [comment]
I'm fine with this and not particularly worried about py3 < py36, but of course it's good to be consistent about what we're supporting and not needlessly have missing deps.

**Comment by nieder** [comment]
What's the status here? Seems to all be in agreement?

**Comment by dmacks** [comment]
Conflict resolved, so let's do this thang...

**Pull request merged**
