### PR TITLE
rustc 1.23.0

### PR DESCRIPTION
**Pull request by bcully**

### CODE REVIEW

**Comment by dmacks** [comment]
Are those shared libraries actually for public linking by other compiled programs, or are they merely shared among various binaries that are in the rustc package itself? They all appear to have changed names, so if other programs or packages' binaries had been compiled previously, will this change break them or require recompiling?

**Comment by bcully** [comment]
I don't know exactly what those libraries are for, but I do know that none of them are linked into anything I've built. I believe they are just shared for the benefit of all the tools that the compiler ships with, based on the names of the libraries and the fact that the tools link to them but nothing else appears to.

I wish there were a way to get fink to ignore these shared libraries, honestly.

**Comment by dmacks** [comment]
Sounds like a perfect example of "Private Shared Libraries", which have a slight variation on the Shlibs field syntax.

**Comment by dmacks** [comment]
Less data for you to update each time and less confusing for others using it, but still pain-ish.

**Comment by bcully** [comment]
Updated to use private shlibs

**Pull request merged**
