### PR TITLE
new gcc11 package

### PR DESCRIPTION
**Pull request by nieder**
New package for gcc11 upstream.

### CODE REVIEW

**Comment by dmacks** [comment]
Centralizing nieder's comment from #844: "seems to be working everywhere I've tested so far (10.14, 10.14.5, 10.15, and 11.0; 11.3 build going)". To which I'll add that it built in -m mode on my 10.13 box.

**Comment by nieder** [comment]
On 11.5 (not 11.0.1) with Xcode 12.5.1, there's this failure:
```
rm -f stage_current
Comparing stages 2 and 3
warning: gcc/cc1obj-checksum.o differs
warning: gcc/cc1objplus-checksum.o differs
Bootstrap comparison failure!
gcc/tree-ssa-operands.o differs
gcc/tree-ssanames.o differs
gcc/ipa-inline.o differs
gcc/tree-ssa-pre.o differs
gcc/gimple-loop-interchange.o differs
gcc/collect2.o differs
gcc/tree-ssa-loop-split.o differs
gcc/tree-eh.o differs
gcc/tree-vect-loop.o differs
gcc/tree-iterator.o differs
gcc/gengtype-state.o differs
gcc/tree-ssa-loop-unswitch.o differs
gcc/tree-ssa-sccvn.o differs
gcc/optabs.o differs
gcc/dfp.o differs
gcc/x86-tune-sched-bd.o differs
gcc/gimple-ssa-isolate-paths.o differs
gcc/insn-latencytab.o differs
gcc/insn-dfatab.o differs
gcc/read-md.o differs
gcc/ipa-inline-transform.o differs
gcc/generic-match.o differs
gcc/early-remat.o differs
gcc/haifa-sched.o differs
gcc/ira-emit.o differs
gcc/tree-vect-slp.o differs
gcc/profile-count.o differs
gcc/tree-predcom.o differs
gcc/varasm.o differs
gcc/ipa-utils.o differs
gcc/auto-profile.o differs
gcc/varpool.o differs
gcc/tree-ssa-reassoc.o differs
...
libiberty/dyn-string.o differs
libiberty/cplus-dem.o differs
libiberty/vprintf-support.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
```
And confirmed on fink-beginners by Chris Schram. So I don't know why stage3 is building differently, but it only affects one OS at this point.

**Comment by nieder** [comment]
Now confirmed by myself and Chris Schram that Xcode13 fixes the build on BigSur.

**Comment by nieder** [comment]
This is the upstream bug about stage3 differing from stage2 when using Xcode12.5:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100340

**Comment by dmacks** [comment]
Is it time to push this?

**Comment by nieder** [comment]
Sure. I think the only bug was that Xcode13 was needed on Big Sur. They haven't released the fix that makes it xcode agnostic, but everyone on Big Sur should be on that.

**Comment by nieder** [comment]
gcc9 is not building on macOS 12. There's a (correctly?) patchable missing symbols problem, but then there's a segfault. We might need to the get this and transition packages to gcc11

**Comment by nieder** [comment]
Pushing this because a lot of things are going to need to use it.

**Pull request merged**
