### PR TITLE
mbsystem 5.7.6

### PR DESCRIPTION
**Pull request by PovlAbrahamsen**
Latest release of mbsystem.
This PR depends on #693 and #695. Maintainer is @schwehr. 
Changes:
- use latest netcdf, proj, and GMT libraries.
- update source location to Github, remove second source, since Levitus82 database is provided within main distribution.
- custom install script no longer required.
- enable tests (require python 3.6 or above).
- add a note about flat namespaces for libxt...

### CODE REVIEW

**Comment by schwehr** [comment]
I'm not working on fink or mbsystem anymore.  Please remove me from the `Maintainer` field.

**Comment by PovlAbrahamsen** [comment]
Sorry, I accidentally merged commits from the wrong branch! Please cherry-pick 0c8eeaf  and e103f6a - or I can close and make a new PR...

**Comment by nieder** [comment]
I've cherry picked the two mbsystem commits into HEAD as requested. Closing this and you can kill your branch if you want.

**Comment by dmacks** [comment]
> I'm not working on fink or mbsystem anymore. Please remove me from the `Maintainer` field.

Thanks for all your work on fink over the years!

**Pull request closed without merging**
