### PR TITLE
New upstream version of rkhunter

### PR DESCRIPTION
**Pull request by mommsen**
Update rkhunter to version 1.4.6

### CODE REVIEW

**Comment by nieder** [comment]
The build has a lot of lines like:
```
chown: ./files: Operation not permitted
```
Is this expected?

**Comment by mommsen** [comment]
Yes, the build scripts is changing the file permissions to root, which fink-bld is not allowed to. During the installation step (run as root), this is rectified.

**Comment by dmacks** [comment]
Teeny nit: usually good practice to reset Revision to 1 when upgrading Version.
Possible improvement: fink has several variants of wget, but this package has a dependency only on one of them. Users might appreciate being able to use a different one (the differences seem mostly internal, so I assume other variants would suffice). Instead of ```wget```, use ```wget | wget-gnutls | wget-idn | wget-gnutls-idn```

**Comment by dmacks** [comment]
Probably best to patch install.sh to omit the chmod. No sense giving diagnostics that look like a problem (a non-detected error leading to a misbuilt package?) that aren't.

**Comment by mommsen** [comment]
At some point in the past, we started using higher revisions for the latest tree in order to be able to pack port packages to older trees. I don't mind to reset the revision to 1 as there are no older trees maintained anymore.

The wget package indeed provides different variants, but also defines the virtual package gnu-wget. Thus, I think it would be enough to depend on gnu-wget, isn't it?

I'll see if I can patch the install.sh. IIRC, the same method is used during the compile and install cycle. The chmod is needed in the latter. I'll see if I can patch it. However, nobody has complained about it since fink started using fink-bld by default years ago....

**Comment by mommsen** [comment]
@dmacks, can you please check if your concerns have been addressed by commit 5b2c15f?

Thanks,
Remi

**Comment by mommsen** [comment]
ping @dmacks (;

**Pull request merged**
