### PR TITLE
SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf

### PR DESCRIPTION
**Pull request by nieder**
SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf. Based on the current SDL1 packages.
I can take them over if desired.

### CODE REVIEW

**Comment by sth0** [comment]
> On Nov 19, 2019, at 7:08 AM, nieder <notifications@github.com> wrote:
> 
> SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf. Based on the current SDL1 packages.
> I can take them over if desired.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/fink/fink-distributions/pull/515 <https://github.com/fink/fink-distributions/pull/515>There is still a problem with SDL2 on older systems.   It will not install on 10.11.6 though is nominally listed for this system.  Do we need to roll back the version for 10.11 systems?  Or update with a patch?

I have included the output with most of the unpacking, configuration, and some compiling removed.  I get 3 warnings and 2 errors.

The error problem is "use of undeclared identifier ‘NSEventSubtypeMouseEvent’” which may only be present on newer systems??  A bit of googling seems to infer that MacPorts has a patch for this.  That the issue is only Mac OS 10.11 and older and newer systems work.
See: https://trac.macports.org/attachment/ticket/58767/10.11-fix.patch <https://trac.macports.org/attachment/ticket/58767/10.11-fix.patch>

It may be that this patch will be in the next release for SDL2??  It is merely a greater or equal to rather than greater than problem.
https://hg.libsdl.org/SDL/rev/449d5819a84a <https://hg.libsdl.org/SDL/rev/449d5819a84a>

-Scott

The package 'sdl2-shlibs' will be built and installed.
Reading build dependency for sdl2-2.0.10-1...
Reading dependency for sdl2-2.0.10-1...
Reading dependency for sdl2-shlibs-2.0.10-1...
Reading build dependency for sdl2-shlibs-2.0.10-1...
Reading dependency for sdl2-shlibs-2.0.10-1...
Reading runtime dependency for sdl2-shlibs-2.0.10-1...
Reading build conflict for sdl2-2.0.10-1...
Reading build conflict for sdl2-shlibs-2.0.10-1...
The following package will be installed or updated:
 sdl2-shlibs
Setting runtime build-lock...
dpkg-deb -b /sw/src/fink.build/root-fink-buildlock-sdl2-2.0.10-1 /sw/src/fink.build
dpkg-deb: building package `fink-buildlock-sdl2-2.0.10-1' in `/sw/src/fink.build/fink-buildlock-sdl2-2.0.10-1_2019.11.09-13.38.57_darwin-x86_64.deb'.
Installing build-lock package...
/sw/bin/dpkg-lockwait -i /sw/src/fink.build/fink-buildlock-sdl2-2.0.10-1_2019.11.09-13.38.57_darwin-x86_64.deb
Selecting previously deselected package fink-buildlock-sdl2-2.0.10-1.
(Reading database ... 225094 files and directories currently installed.)
Unpacking fink-buildlock-sdl2-2.0.10-1 (from .../fink-buildlock-sdl2-2.0.10-1_2019.11.09-13.38.57_darwin-x86_64.deb) ...
Setting up fink-buildlock-sdl2-2.0.10-1 (2019.11.09-13.38.57) ...

sudo -u fink-bld [ENV] sh -c /tmp/fink.kNERl
env LANG=C LC_ALL=C /sw/bin/tar  --no-same-owner --no-same-permissions -xvf /sw/src/SDL2-2.0.10.tar.gz
SDL2-2.0.10/

[...  Deleted Stuff ...]

  CC     build/SDL_cocoamessagebox.lo
  CC     build/SDL_cocoametalview.lo
  CC     build/SDL_cocoamodes.lo
/sw/src/fink.build/sdl2-2.0.10-1/SDL2-2.0.10/src/video/cocoa/SDL_cocoamodes.m:118:11: warning: 'CGDisplayModeCopyPixelEncoding' is deprecated: first deprecated in macOS 10.11 [-Wdeprecated-declarations]
    fmt = CGDisplayModeCopyPixelEncoding(vidmode);
          ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:174:34: note: 'CGDisplayModeCopyPixelEncoding' has been explicitly marked deprecated here
CG_EXTERN CFStringRef __nullable CGDisplayModeCopyPixelEncoding(
                                 ^
/sw/src/fink.build/sdl2-2.0.10-1/SDL2-2.0.10/src/video/cocoa/SDL_cocoamodes.m:172:64: warning: 'CGDisplayIOServicePort' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    CFDictionaryRef deviceInfo = IODisplayCreateInfoDictionary(CGDisplayIOServicePort(displayID), kIODisplayOnlyPreferredName);
                                                               ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:372:24: note: 'CGDisplayIOServicePort' has been explicitly marked deprecated here
CG_EXTERN io_service_t CGDisplayIOServicePort(CGDirectDisplayID display)
                       ^
2 warnings generated.
  CC     build/SDL_cocoamouse.lo
  CC     build/SDL_cocoamousetap.lo
  CC     build/SDL_cocoaopengl.lo
  CC     build/SDL_cocoaopengles.lo
  CC     build/SDL_cocoashape.lo
  CC     build/SDL_cocoavideo.lo
  CC     build/SDL_cocoavulkan.lo
  CC     build/SDL_cocoawindow.lo
/sw/src/fink.build/sdl2-2.0.10-1/SDL2-2.0.10/src/video/cocoa/SDL_cocoawindow.m:1119:52: error: use of undeclared identifier 'NSEventSubtypeMouseEvent'
    const BOOL istrackpad = ([theEvent subtype] == NSEventSubtypeMouseEvent);
                                                   ^
/sw/src/fink.build/sdl2-2.0.10-1/SDL2-2.0.10/src/video/cocoa/SDL_cocoawindow.m:1164:52: error: use of undeclared identifier 'NSEventSubtypeMouseEvent'
    const BOOL istrackpad = ([theEvent subtype] == NSEventSubtypeMouseEvent);
                                                   ^
2 errors generated.
make: *** [Makefile:620: build/SDL_cocoawindow.lo] Error 1
make: *** Waiting for unfinished jobs....
### execution of make failed, exit code 2
### execution of /tmp/fink.SD186 failed, exit code 2
Removing runtime build-lock...
Removing build-lock package...
/sw/bin/dpkg-lockwait -r fink-buildlock-sdl2-2.0.10-1
(Reading database ... 225095 files and directories currently installed.)
Removing fink-buildlock-sdl2-2.0.10-1 ...
Failed: phase compiling: sdl2-2.0.10-1 failed

Before reporting any errors, please run "fink selfupdate" and try again.
Also try using "fink configure" to set your maximum build jobs to 1 and
attempt to build the package again.
If you continue to have issues, please check to see if the FAQ on Fink's 
website solves the problem.  If not, ask on one (not both, please) of
these mailing lists:

	The Fink Users List <fink-users@lists.sourceforge.net <mailto:fink-users@lists.sourceforge.net>>
	The Fink Beginners List <fink-beginners@lists.sourceforge.net <mailto:fink-beginners@lists.sourceforge.net>>,

with a carbon copy to the maintainer:

	Max Horn <max@quendi.de <mailto:max@quendi.de>>

Note that this is preferable to emailing just the maintainer directly,
since most fink package maintainers do not have access to all possible
hardware and software configurations.

Please try to include the complete error message in your report.  This
generally consists of a compiler line starting with e.g. "gcc" or "g++"
followed by the actual error output from the compiler.

Also include the following system information:
Package manager version: 0.45.0
Distribution version: selfupdate-git Mon Oct 28 19:36:40 2019, 10.11, x86_64
Trees: local/main stable/main local/injected
Xcode.app: 8.2.1
Xcode command-line tools: 8.2.0.0.1.1480973914
Max. Fink build jobs:  2

**Comment by nieder** [comment]
Thanks. I tested on 10.13, so I missed that. I might be able to power up a 10.10 VM to test the patch.

**Comment by sth0** [comment]
Looking a the link it is a simple change in the file "src/video/cocoa/SDL_cocoavideo.h” from

#if MAC_OS_X_VERSION_MAX_ALLOWED < 101100

to 

#if MAC_OS_X_VERSION_MAX_ALLOWED < 101200

basically group 10.11 as less than 10.12 instead of with the newer systems.  So currently 10.10 will work and 10.11 will try to use the new variable that came along with 10.12.  Testing 10.10 will work.  Testing 10.11 will not.

-Scott

**Comment by nieder** [comment]
@fingolfin do you want me to push the sdl2-2.0.10 fix for 10.11 here in this PR or as a separate thing?

**Comment by nieder** [comment]
The SDL2/10.11 fix from #542 has been pushed.

**Comment by fingolfin** [comment]
@nieder my apologies, for some stupid local reasons, I didn't see the notifications for this.

Thank you for working on this. Clearly I have had far too little time recently to work on anything Fink related. I suggest to remove me as maintainer from those packages, and then go ahead with this PR (or feel free to first do this PR, and remove me later, or whatever else is most convenient).

Again, thank you for working on this and sorry for not responding before.

**Comment by nieder** [comment]
Thanks. Pushed.

**Pull request merged**
