### PR TITLE
vigra: Bump deps

### PR DESCRIPTION
**Pull request by dmacks**
NB: Fixing a bug in hdf test that was previously causing non-detection of
it altgether, at least on current cmake.

### CODE REVIEW

**Comment by dmacks** [comment]
Boost-1.68 wasn't being detected by cmake, so I'm not bumping that dep (my current itch is scratched). Sorry about the PR #900 noise...got my xterms mixed up.

**Comment by nieder** [comment]
This seems to find boost1.68:
```
		-DBoost_DIR=%p/opt/boost-1_68 \
		-DBoost_INCLUDE_DIR=%p/opt/boost-1_68/include \
		-DBoost_PYTHON_LIBRARY_RELEASE:FILEPATH=%p/opt/boost-1_68/lib/libboost_python27-mt.dylib \
```

**Comment by nieder** [comment]
This is OK with me.

**Comment by nieder** [comment]
Closed by 7effc62. Dunno why the PR didn't close with the merge.

**Pull request merged**
