### PR TITLE
airspy: new package

### PR DESCRIPTION
**Pull request by kamischi**

### CODE REVIEW

**Comment by kamischi** [comment]
I exchanged the package name and made some modifications of the package to reflect the comments of dhomeier. With regards to whether it is required to take the git revision, i vote strongly for yes, because there are 14 commits since the last version (1.0.9), with some of them consist of more than trivial changes, i.e. actual code changes. In order to resolve the update issue, I included the date of the revision. 

MiSchi

**Comment by kamischi** [comment]
Can someone cherry pick the commits. The 4 file changes correspond to 3 independent updates (unrar, Pascal-P5, arm-binutils) and one new package (airspyone_host).

**Comment by dmacks** [comment]
I cherry-picked unrar, pascal-p5, and arm-binutils. Doing airspyone_host is harder because it was two different commits, one of which involved a transient different package-name. Should I squash those two together to make a single commit (with a merged commit-message), or cherry-pick them each independently (and edit the commit-message to indicate that it was all happening on a fork rather than the transient package ever existing in fink:master)?

**Comment by kamischi** [comment]
Thanks. I do not completely understand, why to consider two commits, but let me try: The first commit with airspy.info can simply be neglected. The commit with airspyone-host.info is all, what's needed. Does this clear up things?

**Comment by dmacks** [comment]
"The commit with airspyone-host.info" created that file by renaming and lightly editing the airspy.info that had existed previously from an earlier commit. So I can either cherry-pick that sequence of two commits, or combine them into a single one.

**Comment by kamischi** [comment]
I think one is sufficient, since it means less clutter.

**Comment by dmacks** [comment]
Pushed as 991295177d

**Comment by nieder** [comment]
I don't see the tarball on Fink's SF space.

**Comment by kamischi** [comment]
source file is uploaded now.

**Comment by dmacks** [comment]
Thanks!

**Pull request closed without merging**
