### PR TITLE
Library for Just Another Gibbs Sampler

### PR DESCRIPTION
**Pull request by babayoshihiko**
A new package. I am testing this new package with R through rjags package and so far it seems working.

### CODE REVIEW

**Comment by nieder** [comment]
Wondering about the splitoff layout.

1) manfile is in libjags4-shlibs package while executable is in libjags4 splitoff.
2) The various .la files are in libjags4-shlibs. Are they needed at runtime by things using the library, or do they belong in the BDO libjags?

`libjags4` links to libtool2-shlibs

**Comment by babayoshihiko** [comment]
Fiexed them.

Another question; is "sci" a good category?

**Comment by nieder** [comment]
Ugh. Didn't notice that the .pc file is also in the -shlibs splitoff.

**Comment by babayoshihiko** [comment]
> Ugh. Didn't notice that the .pc file is also in the -shlibs splitoff.

Should I move the whole pkgconfig to the SplitOff? (Add lib/pkgconfig to Files in the SplitOff)?

**Comment by nieder** [comment]
yes please. Nothing in that directory belongs with the shlibs files.

**Comment by babayoshihiko** [comment]
> yes please. Nothing in that directory belongs with the shlibs files.

Fixed.

**Review by nieder — APPROVED** [review]

**Pull request merged**
